// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package repo

import (
	"context"
)

const findProductByID = `-- name: FindProductByID :one
SELECT id, name, price_in_centers, quantity, created_at
FROM products
WHERE id = $1
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRow(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCenters,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const findProductsByQuery = `-- name: FindProductsByQuery :many
SELECT id, name, price_in_centers, quantity, created_at
FROM products
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
  AND (
    $2::int = 0
    OR price_in_centers = $2
  )
`

type FindProductsByQueryParams struct {
	Name           string `json:"name"`
	PriceInCenters int32  `json:"price_in_centers"`
}

func (q *Queries) FindProductsByQuery(ctx context.Context, arg FindProductsByQueryParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, findProductsByQuery, arg.Name, arg.PriceInCenters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCenters,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_centers, quantity, created_at
FROM products
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCenters,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
