// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFCMToken = `-- name: ClearFCMToken :exec
DELETE FROM device_tokens
WHERE fcm_token = $1 AND user_id = $2
`

type ClearFCMTokenParams struct {
	FcmToken string      `json:"fcm_token"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Gọi khi Firebase báo token không còn hợp lệ (người dùng gỡ app). Xoá hẳn hàng
// thay vì set NULL: hàng không có token thì không còn ý nghĩa gì, và cột
// fcm_token là NOT NULL.
func (q *Queries) ClearFCMToken(ctx context.Context, arg ClearFCMTokenParams) error {
	_, err := q.db.Exec(ctx, clearFCMToken, arg.FcmToken, arg.UserID)
	return err
}

const countNotificationsByUserID = `-- name: CountNotificationsByUserID :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1
`

func (q *Queries) CountNotificationsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)
FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, payload, read_at, created_at, title, body
`

type CreateNotificationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Type    string      `json:"type"`
	Title   string      `json:"title"`
	Body    string      `json:"body"`
	Payload []byte      `json:"payload"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Payload,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Title,
		&i.Body,
	)
	return i, err
}

const getActiveFCMTokenByUserID = `-- name: GetActiveFCMTokenByUserID :one
SELECT fcm_token
FROM device_tokens
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT 1
`

// Địa chỉ push thuộc về thiết bị, không thuộc về phiên đăng nhập: không lọc theo
// trạng thái phiên ở đây, nếu không thì đúng nhóm người dùng lâu không mở app —
// nhóm cần nhắc nợ nhất — sẽ không bao giờ nhận được thông báo.
func (q *Queries) GetActiveFCMTokenByUserID(ctx context.Context, userID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getActiveFCMTokenByUserID, userID)
	var fcm_token string
	err := row.Scan(&fcm_token)
	return fcm_token, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, type, payload, read_at, created_at, title, body
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
		&i.Title,
		&i.Body,
	)
	return i, err
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT id, user_id, type, payload, read_at, created_at, title, body
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
			&i.Title,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :execrows
UPDATE notifications
SET read_at = COALESCE(read_at, now())
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
