// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Gọi khi Firebase báo token không còn hợp lệ (người dùng gỡ app). Xoá hẳn hàng
	// thay vì set NULL: hàng không có token thì không còn ý nghĩa gì, và cột
	// fcm_token là NOT NULL.
	ClearFCMToken(ctx context.Context, arg ClearFCMTokenParams) error
	CountNotificationsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// Địa chỉ push thuộc về thiết bị, không thuộc về phiên đăng nhập: không lọc theo
	// trạng thái phiên ở đây, nếu không thì đúng nhóm người dùng lâu không mở app —
	// nhóm cần nhắc nợ nhất — sẽ không bao giờ nhận được thông báo.
	GetActiveFCMTokenByUserID(ctx context.Context, userID pgtype.UUID) (string, error)
	GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error)
	ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
