// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearFCMToken(ctx context.Context, fcmToken pgtype.Text) error
	CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	GetActiveFCMTokenByUserID(ctx context.Context, userID pgtype.UUID) (pgtype.Text, error)
	ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
