services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: paysplit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d paysplit"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - paysplit_postgres18_data:/var/lib/postgresql

volumes:
  paysplit_postgres_data:
  paysplit_postgres18_data:
