// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	GetTransactionMatchStatus(ctx context.Context, id int64) (GetTransactionMatchStatusRow, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error)
	// Chỉ lần xử lý đầu tiên được ghi: hai lần SePay gửi trùng chạy song song thì
	// kết quả của lần gạch nợ thật (confirmed) không bị already_confirmed đè lên.
	MarkTransactionProcessed(ctx context.Context, arg MarkTransactionProcessedParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
