// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sepay.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTransactionMatchStatus = `-- name: GetTransactionMatchStatus :one
SELECT match_status, payment_id FROM sepay_transactions WHERE id = $1
`

type GetTransactionMatchStatusRow struct {
	MatchStatus pgtype.Text `json:"match_status"`
	PaymentID   pgtype.UUID `json:"payment_id"`
}

func (q *Queries) GetTransactionMatchStatus(ctx context.Context, id int64) (GetTransactionMatchStatusRow, error) {
	row := q.db.QueryRow(ctx, getTransactionMatchStatus, id)
	var i GetTransactionMatchStatusRow
	err := row.Scan(&i.MatchStatus, &i.PaymentID)
	return i, err
}

const insertTransaction = `-- name: InsertTransaction :execrows
INSERT INTO sepay_transactions (
    id, gateway, transaction_date, account_number, sub_account, code, content,
    transfer_type, transfer_amount, accumulated, reference_code, description,
    payment_reference, raw_payload
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (id) DO NOTHING
`

type InsertTransactionParams struct {
	ID               int64              `json:"id"`
	Gateway          string             `json:"gateway"`
	TransactionDate  pgtype.Timestamptz `json:"transaction_date"`
	AccountNumber    string             `json:"account_number"`
	SubAccount       pgtype.Text        `json:"sub_account"`
	Code             pgtype.Text        `json:"code"`
	Content          string             `json:"content"`
	TransferType     string             `json:"transfer_type"`
	TransferAmount   int64              `json:"transfer_amount"`
	Accumulated      int64              `json:"accumulated"`
	ReferenceCode    pgtype.Text        `json:"reference_code"`
	Description      string             `json:"description"`
	PaymentReference pgtype.Text        `json:"payment_reference"`
	RawPayload       []byte             `json:"raw_payload"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTransaction,
		arg.ID,
		arg.Gateway,
		arg.TransactionDate,
		arg.AccountNumber,
		arg.SubAccount,
		arg.Code,
		arg.Content,
		arg.TransferType,
		arg.TransferAmount,
		arg.Accumulated,
		arg.ReferenceCode,
		arg.Description,
		arg.PaymentReference,
		arg.RawPayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTransactionProcessed = `-- name: MarkTransactionProcessed :execrows
UPDATE sepay_transactions
SET match_status = $2, payment_id = $3, processed_at = now()
WHERE id = $1 AND match_status IS NULL
`

type MarkTransactionProcessedParams struct {
	ID          int64       `json:"id"`
	MatchStatus pgtype.Text `json:"match_status"`
	PaymentID   pgtype.UUID `json:"payment_id"`
}

// Chỉ lần xử lý đầu tiên được ghi: hai lần SePay gửi trùng chạy song song thì
// kết quả của lần gạch nợ thật (confirmed) không bị already_confirmed đè lên.
func (q *Queries) MarkTransactionProcessed(ctx context.Context, arg MarkTransactionProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTransactionProcessed, arg.ID, arg.MatchStatus, arg.PaymentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
