// Placeholder for code that will be generated by sqlc.

package sqlc

import "context"

type CreateUserParams struct {
	Email        string `json:"email"`
	Name         string `json:"name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	panic("TODO: generate with sqlc")
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	panic("TODO: generate with sqlc")
}
