// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, phone_number, display_name, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, avatar_object_key, phone_number, default_bank_code, default_bank_account_number, default_bank_account_holder, role, status, email_verified_at, created_at, updated_at, failed_login_count, failed_login_window_started_at, login_blocked_until
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PhoneNumber  string `json:"phone_number"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PhoneNumber,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.PhoneNumber,
		&i.DefaultBankCode,
		&i.DefaultBankAccountNumber,
		&i.DefaultBankAccountHolder,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginCount,
		&i.FailedLoginWindowStartedAt,
		&i.LoginBlockedUntil,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, avatar_object_key, phone_number, default_bank_code, default_bank_account_number, default_bank_account_holder, role, status, email_verified_at, created_at, updated_at, failed_login_count, failed_login_window_started_at, login_blocked_until
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.PhoneNumber,
		&i.DefaultBankCode,
		&i.DefaultBankAccountNumber,
		&i.DefaultBankAccountHolder,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginCount,
		&i.FailedLoginWindowStartedAt,
		&i.LoginBlockedUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, avatar_object_key, phone_number, default_bank_code, default_bank_account_number, default_bank_account_holder, role, status, email_verified_at, created_at, updated_at, failed_login_count, failed_login_window_started_at, login_blocked_until
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.PhoneNumber,
		&i.DefaultBankCode,
		&i.DefaultBankAccountNumber,
		&i.DefaultBankAccountHolder,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginCount,
		&i.FailedLoginWindowStartedAt,
		&i.LoginBlockedUntil,
	)
	return i, err
}
