// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMembers = `-- name: CountActiveMembers :one
SELECT count(*) FROM group_members WHERE group_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveMembers(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenDebts = `-- name: CountOpenDebts :one
SELECT count(*) FROM debts
WHERE group_id = $1 AND status NOT IN ('settled', 'voided')
`

func (q *Queries) CountOpenDebts(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenDebts, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnfinishedBills = `-- name: CountUnfinishedBills :one
SELECT count(*) FROM bills
WHERE group_id = $1 AND status NOT IN ('finalized', 'voided')
`

func (q *Queries) CountUnfinishedBills(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnfinishedBills, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, currency, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, currency, created_by, created_at, status
`

type CreateGroupParams struct {
	Name      string      `json:"name"`
	Currency  string      `json:"currency"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Currency, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const createInitialCaptainMembership = `-- name: CreateInitialCaptainMembership :one
INSERT INTO group_members (group_id, user_id, role, status)
VALUES ($1, $2, 'captain', 'active')
RETURNING id, group_id, user_id, role, status, joined_at, left_at
`

type CreateInitialCaptainMembershipParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateInitialCaptainMembership(ctx context.Context, arg CreateInitialCaptainMembershipParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createInitialCaptainMembership, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO group_invites (group_id, code, created_by, expires_at, max_uses)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, group_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at
`

type CreateInviteParams struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	Code      string             `json:"code"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   pgtype.Int4        `json:"max_uses"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.GroupID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const demoteToMember = `-- name: DemoteToMember :exec
UPDATE group_members SET role = 'member' WHERE id = $1
`

func (q *Queries) DemoteToMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, demoteToMember, id)
	return err
}

const findAvailableInvite = `-- name: FindAvailableInvite :one
SELECT id, group_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at FROM group_invites
WHERE group_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
  AND (max_uses IS NULL OR use_count < max_uses)
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

type FindAvailableInviteParams struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) FindAvailableInvite(ctx context.Context, arg FindAvailableInviteParams) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, findAvailableInvite, arg.GroupID, arg.ExpiresAt)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveCaptainDisplayName = `-- name: GetActiveCaptainDisplayName :one
SELECT u.display_name
FROM group_members m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1 AND m.role = 'captain' AND m.status = 'active'
`

func (q *Queries) GetActiveCaptainDisplayName(ctx context.Context, groupID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getActiveCaptainDisplayName, groupID)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const getActiveMembership = `-- name: GetActiveMembership :one
SELECT id, group_id, user_id, role, status, joined_at, left_at FROM group_members WHERE group_id = $1 AND user_id = $2 AND status = 'active'
`

type GetActiveMembershipParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getActiveMembership, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, currency, created_by, created_at, status FROM groups WHERE id = $1 AND status = 'active'
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, group_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at FROM group_invites WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByCodeForUpdate = `-- name: GetInviteByCodeForUpdate :one
SELECT id, group_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at FROM group_invites WHERE code = $1 FOR UPDATE
`

func (q *Queries) GetInviteByCodeForUpdate(ctx context.Context, code string) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByCodeForUpdate, code)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByIDForGroup = `-- name: GetInviteByIDForGroup :one
SELECT id, group_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at FROM group_invites WHERE id = $1 AND group_id = $2 FOR UPDATE
`

type GetInviteByIDForGroupParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetInviteByIDForGroup(ctx context.Context, arg GetInviteByIDForGroupParams) (GroupInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByIDForGroup, arg.ID, arg.GroupID)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteGroupIDByCode = `-- name: GetInviteGroupIDByCode :one
SELECT i.group_id
FROM group_invites i
JOIN groups g ON g.id = i.group_id AND g.status = 'active'
WHERE i.code = $1
`

func (q *Queries) GetInviteGroupIDByCode(ctx context.Context, code string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getInviteGroupIDByCode, code)
	var group_id pgtype.UUID
	err := row.Scan(&group_id)
	return group_id, err
}

const getMembershipByUserForUpdate = `-- name: GetMembershipByUserForUpdate :one
SELECT id, group_id, user_id, role, status, joined_at, left_at FROM group_members WHERE group_id = $1 AND user_id = $2 FOR UPDATE
`

type GetMembershipByUserForUpdateParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMembershipByUserForUpdate(ctx context.Context, arg GetMembershipByUserForUpdateParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserForUpdate, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getUserDisplayName = `-- name: GetUserDisplayName :one
SELECT display_name FROM users WHERE id = $1
`

func (q *Queries) GetUserDisplayName(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserDisplayName, id)
	var display_name string
	err := row.Scan(&display_name)
	return display_name, err
}

const incrementInviteUse = `-- name: IncrementInviteUse :exec
UPDATE group_invites SET use_count = use_count + 1 WHERE id = $1
`

func (q *Queries) IncrementInviteUse(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementInviteUse, id)
	return err
}

const insertMembership = `-- name: InsertMembership :one
INSERT INTO group_members (group_id, user_id, role, status)
VALUES ($1, $2, 'member', 'active')
RETURNING id, group_id, user_id, role, status, joined_at, left_at
`

type InsertMembershipParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, insertMembership, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const listActiveGroupsForUser = `-- name: ListActiveGroupsForUser :many
SELECT g.id, g.name, g.currency, g.created_by, g.created_at,
       m.id AS membership_id, m.role,
       (SELECT count(*) FROM group_members am WHERE am.group_id = g.id AND am.status = 'active') AS active_member_count
FROM group_members m
JOIN groups g ON g.id = m.group_id
WHERE m.user_id = $1
  AND m.status = 'active'
  AND g.status = 'active'
  AND ($3::timestamptz IS NULL
       OR (g.created_at, g.id) < ($3::timestamptz, $4::uuid))
ORDER BY g.created_at DESC, g.id DESC
LIMIT $2
`

type ListActiveGroupsForUserParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	Limit           int32              `json:"limit"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

type ListActiveGroupsForUserRow struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Currency          string             `json:"currency"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	MembershipID      pgtype.UUID        `json:"membership_id"`
	Role              interface{}        `json:"role"`
	ActiveMemberCount int64              `json:"active_member_count"`
}

func (q *Queries) ListActiveGroupsForUser(ctx context.Context, arg ListActiveGroupsForUserParams) ([]ListActiveGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveGroupsForUser,
		arg.UserID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveGroupsForUserRow
	for rows.Next() {
		var i ListActiveGroupsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.MembershipID,
			&i.Role,
			&i.ActiveMemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMembers = `-- name: ListActiveMembers :many
SELECT m.id AS membership_id, m.user_id, u.display_name, u.avatar_object_key, m.role, m.joined_at
FROM group_members m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1 AND m.status = 'active'
ORDER BY m.joined_at ASC, m.id ASC
`

type ListActiveMembersRow struct {
	MembershipID    pgtype.UUID        `json:"membership_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	DisplayName     string             `json:"display_name"`
	AvatarObjectKey pgtype.Text        `json:"avatar_object_key"`
	Role            interface{}        `json:"role"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListActiveMembers(ctx context.Context, groupID pgtype.UUID) ([]ListActiveMembersRow, error) {
	rows, err := q.db.Query(ctx, listActiveMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMembersRow
	for rows.Next() {
		var i ListActiveMembersRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.DisplayName,
			&i.AvatarObjectKey,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableInvites = `-- name: ListAvailableInvites :many
SELECT id, group_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at FROM group_invites
WHERE group_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
  AND (max_uses IS NULL OR use_count < max_uses)
ORDER BY created_at DESC, id DESC
`

type ListAvailableInvitesParams struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ListAvailableInvites(ctx context.Context, arg ListAvailableInvitesParams) ([]GroupInvite, error) {
	rows, err := q.db.Query(ctx, listAvailableInvites, arg.GroupID, arg.ExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupInvite
	for rows.Next() {
		var i GroupInvite
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Code,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupActivities = `-- name: ListGroupActivities :many
SELECT a.id, a.action_type, a.description, a.metadata, a.created_at,
       m.id AS actor_membership_id, m.user_id, u.display_name, u.avatar_object_key
FROM group_activities a
JOIN group_members m ON m.id = a.actor_member_id
JOIN users u ON u.id = m.user_id
WHERE a.group_id = $1
  AND ($3::timestamptz IS NULL
       OR (a.created_at, a.id) < ($3::timestamptz, $4::uuid))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $2
`

type ListGroupActivitiesParams struct {
	GroupID         pgtype.UUID        `json:"group_id"`
	Limit           int32              `json:"limit"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

type ListGroupActivitiesRow struct {
	ID                pgtype.UUID        `json:"id"`
	ActionType        interface{}        `json:"action_type"`
	Description       string             `json:"description"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ActorMembershipID pgtype.UUID        `json:"actor_membership_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	DisplayName       string             `json:"display_name"`
	AvatarObjectKey   pgtype.Text        `json:"avatar_object_key"`
}

func (q *Queries) ListGroupActivities(ctx context.Context, arg ListGroupActivitiesParams) ([]ListGroupActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listGroupActivities,
		arg.GroupID,
		arg.Limit,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupActivitiesRow
	for rows.Next() {
		var i ListGroupActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.Description,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorMembershipID,
			&i.UserID,
			&i.DisplayName,
			&i.AvatarObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupBalances = `-- name: ListGroupBalances :many
SELECT b.member_id, b.net_balance::bigint AS net_balance
FROM v_member_balances b
JOIN group_members m ON m.id = b.member_id AND m.group_id = b.group_id
WHERE b.group_id = $1 AND m.status = 'active'
ORDER BY m.joined_at ASC, m.id ASC
`

type ListGroupBalancesRow struct {
	MemberID   pgtype.UUID `json:"member_id"`
	NetBalance int64       `json:"net_balance"`
}

func (q *Queries) ListGroupBalances(ctx context.Context, groupID pgtype.UUID) ([]ListGroupBalancesRow, error) {
	rows, err := q.db.Query(ctx, listGroupBalances, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupBalancesRow
	for rows.Next() {
		var i ListGroupBalancesRow
		if err := rows.Scan(&i.MemberID, &i.NetBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGroup = `-- name: LockGroup :one
SELECT id FROM groups WHERE id = $1 AND status = 'active' FOR UPDATE
`

func (q *Queries) LockGroup(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockGroup, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockMembership = `-- name: LockMembership :one
SELECT id, group_id, user_id, role, status, joined_at, left_at FROM group_members WHERE id = $1 AND group_id = $2 FOR UPDATE
`

type LockMembershipParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) LockMembership(ctx context.Context, arg LockMembershipParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, lockMembership, arg.ID, arg.GroupID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const markMembershipInactive = `-- name: MarkMembershipInactive :exec
UPDATE group_members SET status = 'inactive', left_at = $2 WHERE id = $1
`

type MarkMembershipInactiveParams struct {
	ID     pgtype.UUID        `json:"id"`
	LeftAt pgtype.Timestamptz `json:"left_at"`
}

func (q *Queries) MarkMembershipInactive(ctx context.Context, arg MarkMembershipInactiveParams) error {
	_, err := q.db.Exec(ctx, markMembershipInactive, arg.ID, arg.LeftAt)
	return err
}

const promoteToCaptain = `-- name: PromoteToCaptain :exec
UPDATE group_members SET role = 'captain' WHERE id = $1
`

func (q *Queries) PromoteToCaptain(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, promoteToCaptain, id)
	return err
}

const reactivateMembership = `-- name: ReactivateMembership :one
UPDATE group_members
SET status = 'active', role = 'member', left_at = NULL, joined_at = $2
WHERE id = $1
RETURNING id, group_id, user_id, role, status, joined_at, left_at
`

type ReactivateMembershipParams struct {
	ID       pgtype.UUID        `json:"id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ReactivateMembership(ctx context.Context, arg ReactivateMembershipParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, reactivateMembership, arg.ID, arg.JoinedAt)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const renameGroup = `-- name: RenameGroup :one
UPDATE groups
SET name = $2
WHERE id = $1 AND status = 'active'
RETURNING id, name, currency, created_by, created_at, status
`

type RenameGroupParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, renameGroup, arg.ID, arg.Name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const revokeAvailableInvites = `-- name: RevokeAvailableInvites :many
UPDATE group_invites
SET revoked_at = $2
WHERE group_id = $1
  AND revoked_at IS NULL
  AND expires_at > $2
  AND (max_uses IS NULL OR use_count < max_uses)
RETURNING id, group_id, code, created_by, expires_at, max_uses, use_count, revoked_at, created_at
`

type RevokeAvailableInvitesParams struct {
	GroupID   pgtype.UUID        `json:"group_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeAvailableInvites(ctx context.Context, arg RevokeAvailableInvitesParams) ([]GroupInvite, error) {
	rows, err := q.db.Query(ctx, revokeAvailableInvites, arg.GroupID, arg.RevokedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupInvite
	for rows.Next() {
		var i GroupInvite
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Code,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInviteByID = `-- name: RevokeInviteByID :exec
UPDATE group_invites SET revoked_at = $2 WHERE id = $1
`

type RevokeInviteByIDParams struct {
	ID        pgtype.UUID        `json:"id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeInviteByID(ctx context.Context, arg RevokeInviteByIDParams) error {
	_, err := q.db.Exec(ctx, revokeInviteByID, arg.ID, arg.RevokedAt)
	return err
}

const sumOpenCreditorTotal = `-- name: SumOpenCreditorTotal :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM debts
WHERE group_id = $1 AND creditor_member_id = $2 AND status NOT IN ('settled', 'voided')
`

type SumOpenCreditorTotalParams struct {
	GroupID          pgtype.UUID `json:"group_id"`
	CreditorMemberID pgtype.UUID `json:"creditor_member_id"`
}

func (q *Queries) SumOpenCreditorTotal(ctx context.Context, arg SumOpenCreditorTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumOpenCreditorTotal, arg.GroupID, arg.CreditorMemberID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumOpenDebtorTotal = `-- name: SumOpenDebtorTotal :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total
FROM debts
WHERE group_id = $1 AND debtor_member_id = $2 AND status NOT IN ('settled', 'voided')
`

type SumOpenDebtorTotalParams struct {
	GroupID        pgtype.UUID `json:"group_id"`
	DebtorMemberID pgtype.UUID `json:"debtor_member_id"`
}

func (q *Queries) SumOpenDebtorTotal(ctx context.Context, arg SumOpenDebtorTotalParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumOpenDebtorTotal, arg.GroupID, arg.DebtorMemberID)
	var total int64
	err := row.Scan(&total)
	return total, err
}
