// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveMembers(ctx context.Context, groupID pgtype.UUID) (int64, error)
	CountOpenDebts(ctx context.Context, groupID pgtype.UUID) (int64, error)
	CountUnfinishedBills(ctx context.Context, groupID pgtype.UUID) (int64, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateInitialCaptainMembership(ctx context.Context, arg CreateInitialCaptainMembershipParams) (GroupMember, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (GroupInvite, error)
	DemoteToMember(ctx context.Context, id pgtype.UUID) error
	FindAvailableInvite(ctx context.Context, arg FindAvailableInviteParams) (GroupInvite, error)
	GetActiveCaptainDisplayName(ctx context.Context, groupID pgtype.UUID) (string, error)
	GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (GroupMember, error)
	// ============================================================================
	// GROUP BILL CLOSE V1 (Spec 0008): điều hướng batch của Captain và rào chắn archive
	// ============================================================================
	GetBillFinalizeBatchNavigation(ctx context.Context, groupID pgtype.UUID) (GetBillFinalizeBatchNavigationRow, error)
	GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error)
	GetInviteByCode(ctx context.Context, code string) (GroupInvite, error)
	GetInviteByCodeForUpdate(ctx context.Context, code string) (GroupInvite, error)
	GetInviteByIDForGroup(ctx context.Context, arg GetInviteByIDForGroupParams) (GroupInvite, error)
	GetInviteGroupIDByCode(ctx context.Context, code string) (pgtype.UUID, error)
	GetMembershipByUserForUpdate(ctx context.Context, arg GetMembershipByUserForUpdateParams) (GroupMember, error)
	GetUserDisplayName(ctx context.Context, id pgtype.UUID) (string, error)
	IncrementInviteUse(ctx context.Context, id pgtype.UUID) error
	InsertMembership(ctx context.Context, arg InsertMembershipParams) (GroupMember, error)
	// Mỗi hàng mang đủ dữ liệu cho một thẻ nhóm ở FE nên danh sách không cần
	// gọi thêm GET /groups/{id} cho từng nhóm (báo cáo đối chiếu mục 3.2, 3.3).
	ListActiveGroupsForUser(ctx context.Context, arg ListActiveGroupsForUserParams) ([]ListActiveGroupsForUserRow, error)
	ListActiveMembers(ctx context.Context, groupID pgtype.UUID) ([]ListActiveMembersRow, error)
	ListAvailableInvites(ctx context.Context, arg ListAvailableInvitesParams) ([]GroupInvite, error)
	ListGroupActivities(ctx context.Context, arg ListGroupActivitiesParams) ([]ListGroupActivitiesRow, error)
	ListGroupBalances(ctx context.Context, groupID pgtype.UUID) ([]ListGroupBalancesRow, error)
	LockGroup(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	LockMembership(ctx context.Context, arg LockMembershipParams) (GroupMember, error)
	MarkMembershipInactive(ctx context.Context, arg MarkMembershipInactiveParams) error
	PromoteToCaptain(ctx context.Context, id pgtype.UUID) error
	ReactivateMembership(ctx context.Context, arg ReactivateMembershipParams) (GroupMember, error)
	RenameGroup(ctx context.Context, arg RenameGroupParams) (Group, error)
	RevokeAvailableInvites(ctx context.Context, arg RevokeAvailableInvitesParams) ([]GroupInvite, error)
	RevokeInviteByID(ctx context.Context, arg RevokeInviteByIDParams) error
	SumOpenCreditorTotal(ctx context.Context, arg SumOpenCreditorTotalParams) (int64, error)
	SumOpenDebtorTotal(ctx context.Context, arg SumOpenDebtorTotalParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
