// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAccounts = `-- name: CountAccounts :one
SELECT count(*)::bigint AS total
FROM users
WHERE
    ($1::text IS NULL OR $1::text = '' OR email ILIKE '%' || $1::text || '%' OR display_name ILIKE '%' || $1::text || '%' OR phone_number ILIKE '%' || $1::text || '%')
    AND ($2::text IS NULL OR $2::text = '' OR status = $2::account_status)
    AND ($3::text IS NULL OR $3::text = '' OR role = $3::user_role)
`

type CountAccountsParams struct {
	Search pgtype.Text `json:"search"`
	Status pgtype.Text `json:"status"`
	Role   pgtype.Text `json:"role"`
}

func (q *Queries) CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccounts, arg.Search, arg.Status, arg.Role)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countActiveSessionsByUserID = `-- name: CountActiveSessionsByUserID :one
SELECT count(*)::bigint AS active_sessions_count
FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) CountActiveSessionsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByUserID, userID)
	var active_sessions_count int64
	err := row.Scan(&active_sessions_count)
	return active_sessions_count, err
}

const createAdminAuditLog = `-- name: CreateAdminAuditLog :one
INSERT INTO admin_audit_logs (admin_id, target_user_id, action, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, admin_id, target_user_id, action, reason, created_at
`

type CreateAdminAuditLogParams struct {
	AdminID      pgtype.UUID `json:"admin_id"`
	TargetUserID pgtype.UUID `json:"target_user_id"`
	Action       interface{} `json:"action"`
	Reason       string      `json:"reason"`
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAdminAuditLog,
		arg.AdminID,
		arg.TargetUserID,
		arg.Action,
		arg.Reason,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.TargetUserID,
		&i.Action,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT
    id,
    email,
    display_name,
    avatar_object_key,
    phone_number,
    default_bank_code,
    default_bank_account_number,
    default_bank_account_holder,
    role,
    status,
    email_verified_at,
    created_at,
    updated_at,
    failed_login_count,
    login_blocked_until
FROM users
WHERE id = $1
`

type GetAccountByIDRow struct {
	ID                       pgtype.UUID        `json:"id"`
	Email                    string             `json:"email"`
	DisplayName              string             `json:"display_name"`
	AvatarObjectKey          pgtype.Text        `json:"avatar_object_key"`
	PhoneNumber              string             `json:"phone_number"`
	DefaultBankCode          pgtype.Text        `json:"default_bank_code"`
	DefaultBankAccountNumber pgtype.Text        `json:"default_bank_account_number"`
	DefaultBankAccountHolder pgtype.Text        `json:"default_bank_account_holder"`
	Role                     interface{}        `json:"role"`
	Status                   interface{}        `json:"status"`
	EmailVerifiedAt          pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	FailedLoginCount         int32              `json:"failed_login_count"`
	LoginBlockedUntil        pgtype.Timestamptz `json:"login_blocked_until"`
}

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (GetAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i GetAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.PhoneNumber,
		&i.DefaultBankCode,
		&i.DefaultBankAccountNumber,
		&i.DefaultBankAccountHolder,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailedLoginCount,
		&i.LoginBlockedUntil,
	)
	return i, err
}

const getOutstandingCreditsByUserID = `-- name: GetOutstandingCreditsByUserID :one
SELECT
    COALESCE(count(d.id), 0)::bigint AS outstanding_credits_count,
    COALESCE(sum(d.amount), 0)::bigint AS total_credit_amount_vnd
FROM debts d
JOIN group_members gm ON gm.id = d.creditor_member_id
WHERE gm.user_id = $1 AND d.status <> 'settled'
`

type GetOutstandingCreditsByUserIDRow struct {
	OutstandingCreditsCount int64 `json:"outstanding_credits_count"`
	TotalCreditAmountVnd    int64 `json:"total_credit_amount_vnd"`
}

func (q *Queries) GetOutstandingCreditsByUserID(ctx context.Context, userID pgtype.UUID) (GetOutstandingCreditsByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getOutstandingCreditsByUserID, userID)
	var i GetOutstandingCreditsByUserIDRow
	err := row.Scan(&i.OutstandingCreditsCount, &i.TotalCreditAmountVnd)
	return i, err
}

const getOutstandingDebtsByUserID = `-- name: GetOutstandingDebtsByUserID :one
SELECT
    COALESCE(count(d.id), 0)::bigint AS outstanding_debts_count,
    COALESCE(sum(d.amount), 0)::bigint AS total_debt_amount_vnd
FROM debts d
JOIN group_members gm ON gm.id = d.debtor_member_id
WHERE gm.user_id = $1 AND d.status <> 'settled'
`

type GetOutstandingDebtsByUserIDRow struct {
	OutstandingDebtsCount int64 `json:"outstanding_debts_count"`
	TotalDebtAmountVnd    int64 `json:"total_debt_amount_vnd"`
}

func (q *Queries) GetOutstandingDebtsByUserID(ctx context.Context, userID pgtype.UUID) (GetOutstandingDebtsByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getOutstandingDebtsByUserID, userID)
	var i GetOutstandingDebtsByUserIDRow
	err := row.Scan(&i.OutstandingDebtsCount, &i.TotalDebtAmountVnd)
	return i, err
}

const getSystemBillsOverview = `-- name: GetSystemBillsOverview :one
SELECT
    count(*) FILTER (WHERE status = 'finalized')::bigint AS finalized_bills,
    count(*) FILTER (WHERE status = 'draft')::bigint AS draft_bills
FROM bills
`

type GetSystemBillsOverviewRow struct {
	FinalizedBills int64 `json:"finalized_bills"`
	DraftBills     int64 `json:"draft_bills"`
}

func (q *Queries) GetSystemBillsOverview(ctx context.Context) (GetSystemBillsOverviewRow, error) {
	row := q.db.QueryRow(ctx, getSystemBillsOverview)
	var i GetSystemBillsOverviewRow
	err := row.Scan(&i.FinalizedBills, &i.DraftBills)
	return i, err
}

const getSystemDebtsOverview = `-- name: GetSystemDebtsOverview :one
SELECT
    count(*) FILTER (WHERE status = 'awaiting')::bigint AS awaiting_debts,
    count(*) FILTER (WHERE status = 'pending_confirmation')::bigint AS pending_confirmation_debts,
    count(*) FILTER (WHERE status = 'stalled_confirmation')::bigint AS stalled_confirmation_debts,
    count(*) FILTER (WHERE status = 'rejected')::bigint AS rejected_debts,
    count(*) FILTER (WHERE status = 'settled')::bigint AS settled_debts
FROM debts
`

type GetSystemDebtsOverviewRow struct {
	AwaitingDebts            int64 `json:"awaiting_debts"`
	PendingConfirmationDebts int64 `json:"pending_confirmation_debts"`
	StalledConfirmationDebts int64 `json:"stalled_confirmation_debts"`
	RejectedDebts            int64 `json:"rejected_debts"`
	SettledDebts             int64 `json:"settled_debts"`
}

func (q *Queries) GetSystemDebtsOverview(ctx context.Context) (GetSystemDebtsOverviewRow, error) {
	row := q.db.QueryRow(ctx, getSystemDebtsOverview)
	var i GetSystemDebtsOverviewRow
	err := row.Scan(
		&i.AwaitingDebts,
		&i.PendingConfirmationDebts,
		&i.StalledConfirmationDebts,
		&i.RejectedDebts,
		&i.SettledDebts,
	)
	return i, err
}

const getSystemGroupsOverview = `-- name: GetSystemGroupsOverview :one
SELECT count(*)::bigint AS total_groups FROM groups
`

func (q *Queries) GetSystemGroupsOverview(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSystemGroupsOverview)
	var total_groups int64
	err := row.Scan(&total_groups)
	return total_groups, err
}

const getSystemMediaCleanupOverview = `-- name: GetSystemMediaCleanupOverview :one
SELECT count(*)::bigint AS pending_cleanup_jobs FROM media_cleanup_jobs
`

func (q *Queries) GetSystemMediaCleanupOverview(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getSystemMediaCleanupOverview)
	var pending_cleanup_jobs int64
	err := row.Scan(&pending_cleanup_jobs)
	return pending_cleanup_jobs, err
}

const getSystemOCRJobsOverview = `-- name: GetSystemOCRJobsOverview :one
SELECT
    count(*) FILTER (WHERE status = 'queued')::bigint AS queued_jobs,
    count(*) FILTER (WHERE status = 'processing')::bigint AS processing_jobs,
    count(*) FILTER (WHERE status = 'succeeded')::bigint AS succeeded_jobs,
    count(*) FILTER (WHERE status = 'failed')::bigint AS failed_jobs
FROM ocr_jobs
`

type GetSystemOCRJobsOverviewRow struct {
	QueuedJobs     int64 `json:"queued_jobs"`
	ProcessingJobs int64 `json:"processing_jobs"`
	SucceededJobs  int64 `json:"succeeded_jobs"`
	FailedJobs     int64 `json:"failed_jobs"`
}

func (q *Queries) GetSystemOCRJobsOverview(ctx context.Context) (GetSystemOCRJobsOverviewRow, error) {
	row := q.db.QueryRow(ctx, getSystemOCRJobsOverview)
	var i GetSystemOCRJobsOverviewRow
	err := row.Scan(
		&i.QueuedJobs,
		&i.ProcessingJobs,
		&i.SucceededJobs,
		&i.FailedJobs,
	)
	return i, err
}

const getSystemUsersOverview = `-- name: GetSystemUsersOverview :one
SELECT
    count(*)::bigint AS total_users,
    count(*) FILTER (WHERE status = 'active')::bigint AS active_users,
    count(*) FILTER (WHERE status = 'pending_verification')::bigint AS pending_verification_users,
    count(*) FILTER (WHERE status = 'suspended')::bigint AS suspended_users,
    count(*) FILTER (WHERE status = 'locked')::bigint AS locked_users
FROM users
`

type GetSystemUsersOverviewRow struct {
	TotalUsers               int64 `json:"total_users"`
	ActiveUsers              int64 `json:"active_users"`
	PendingVerificationUsers int64 `json:"pending_verification_users"`
	SuspendedUsers           int64 `json:"suspended_users"`
	LockedUsers              int64 `json:"locked_users"`
}

func (q *Queries) GetSystemUsersOverview(ctx context.Context) (GetSystemUsersOverviewRow, error) {
	row := q.db.QueryRow(ctx, getSystemUsersOverview)
	var i GetSystemUsersOverviewRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.PendingVerificationUsers,
		&i.SuspendedUsers,
		&i.LockedUsers,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT
    id,
    email,
    display_name,
    avatar_object_key,
    phone_number,
    role,
    status,
    email_verified_at,
    created_at,
    updated_at
FROM users
WHERE
    ($1::text IS NULL OR $1::text = '' OR email ILIKE '%' || $1::text || '%' OR display_name ILIKE '%' || $1::text || '%' OR phone_number ILIKE '%' || $1::text || '%')
    AND ($2::text IS NULL OR $2::text = '' OR status = $2::account_status)
    AND ($3::text IS NULL OR $3::text = '' OR role = $3::user_role)
ORDER BY
    CASE WHEN $4::text = 'email' AND $5::text = 'asc' THEN email END ASC,
    CASE WHEN $4::text = 'email' AND $5::text = 'desc' THEN email END DESC,
    CASE WHEN $4::text = 'display_name' AND $5::text = 'asc' THEN display_name END ASC,
    CASE WHEN $4::text = 'display_name' AND $5::text = 'desc' THEN display_name END DESC,
    CASE WHEN $4::text = 'created_at' AND $5::text = 'asc' THEN created_at END ASC,
    CASE WHEN ($4::text = 'created_at' OR $4::text = '' OR $4::text IS NULL) AND ($5::text = 'desc' OR $5::text = '' OR $5::text IS NULL) THEN created_at END DESC,
    created_at DESC
LIMIT $7 OFFSET $6
`

type ListAccountsParams struct {
	Search     pgtype.Text `json:"search"`
	Status     pgtype.Text `json:"status"`
	Role       pgtype.Text `json:"role"`
	SortBy     string      `json:"sort_by"`
	SortOrder  string      `json:"sort_order"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

type ListAccountsRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	AvatarObjectKey pgtype.Text        `json:"avatar_object_key"`
	PhoneNumber     string             `json:"phone_number"`
	Role            interface{}        `json:"role"`
	Status          interface{}        `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts,
		arg.Search,
		arg.Status,
		arg.Role,
		arg.SortBy,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarObjectKey,
			&i.PhoneNumber,
			&i.Role,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembershipsByUserID = `-- name: ListGroupMembershipsByUserID :many
SELECT
    gm.group_id,
    g.name AS group_name,
    gm.role AS member_role,
    gm.status AS member_status,
    gm.joined_at
FROM group_members gm
JOIN groups g ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY gm.joined_at DESC
`

type ListGroupMembershipsByUserIDRow struct {
	GroupID      pgtype.UUID        `json:"group_id"`
	GroupName    string             `json:"group_name"`
	MemberRole   interface{}        `json:"member_role"`
	MemberStatus interface{}        `json:"member_status"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListGroupMembershipsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListGroupMembershipsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembershipsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembershipsByUserIDRow
	for rows.Next() {
		var i ListGroupMembershipsByUserIDRow
		if err := rows.Scan(
			&i.GroupID,
			&i.GroupName,
			&i.MemberRole,
			&i.MemberStatus,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAuditLogsByTargetUserID = `-- name: ListRecentAuditLogsByTargetUserID :many
SELECT
    al.id,
    al.admin_id,
    u.email AS admin_email,
    al.target_user_id,
    al.action,
    al.reason,
    al.created_at
FROM admin_audit_logs al
JOIN users u ON u.id = al.admin_id
WHERE al.target_user_id = $1
ORDER BY al.created_at DESC
LIMIT 10
`

type ListRecentAuditLogsByTargetUserIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	AdminID      pgtype.UUID        `json:"admin_id"`
	AdminEmail   string             `json:"admin_email"`
	TargetUserID pgtype.UUID        `json:"target_user_id"`
	Action       interface{}        `json:"action"`
	Reason       string             `json:"reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecentAuditLogsByTargetUserID(ctx context.Context, targetUserID pgtype.UUID) ([]ListRecentAuditLogsByTargetUserIDRow, error) {
	rows, err := q.db.Query(ctx, listRecentAuditLogsByTargetUserID, targetUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentAuditLogsByTargetUserIDRow
	for rows.Next() {
		var i ListRecentAuditLogsByTargetUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminID,
			&i.AdminEmail,
			&i.TargetUserID,
			&i.Action,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshTokensByUserID = `-- name: RevokeRefreshTokensByUserID :exec
UPDATE session_refresh_tokens
SET revoked_at = now()
WHERE session_id IN (SELECT id FROM sessions WHERE user_id = $1) AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByUserID, userID)
	return err
}

const revokeSessionsByUserID = `-- name: RevokeSessionsByUserID :exec
UPDATE sessions
SET revoked_at = now(), revoked_reason = $1
WHERE user_id = $2 AND revoked_at IS NULL
`

type RevokeSessionsByUserIDParams struct {
	RevokedReason pgtype.Text `json:"revoked_reason"`
	UserID        pgtype.UUID `json:"user_id"`
}

func (q *Queries) RevokeSessionsByUserID(ctx context.Context, arg RevokeSessionsByUserIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsByUserID, arg.RevokedReason, arg.UserID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING
    id,
    email,
    display_name,
    avatar_object_key,
    phone_number,
    role,
    status,
    email_verified_at,
    created_at,
    updated_at
`

type UpdateUserStatusParams struct {
	Status interface{} `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

type UpdateUserStatusRow struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	AvatarObjectKey pgtype.Text        `json:"avatar_object_key"`
	PhoneNumber     string             `json:"phone_number"`
	Role            interface{}        `json:"role"`
	Status          interface{}        `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.Status, arg.ID)
	var i UpdateUserStatusRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarObjectKey,
		&i.PhoneNumber,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
