// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAccounts(ctx context.Context, arg CountAccountsParams) (int64, error)
	CountActiveSessionsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error)
	GetAccountByID(ctx context.Context, id pgtype.UUID) (GetAccountByIDRow, error)
	GetOutstandingCreditsByUserID(ctx context.Context, userID pgtype.UUID) (GetOutstandingCreditsByUserIDRow, error)
	GetOutstandingDebtsByUserID(ctx context.Context, userID pgtype.UUID) (GetOutstandingDebtsByUserIDRow, error)
	GetSystemBillsOverview(ctx context.Context) (GetSystemBillsOverviewRow, error)
	GetSystemDebtsOverview(ctx context.Context) (GetSystemDebtsOverviewRow, error)
	GetSystemGroupsOverview(ctx context.Context) (int64, error)
	GetSystemMediaCleanupOverview(ctx context.Context) (int64, error)
	GetSystemOCRJobsOverview(ctx context.Context) (GetSystemOCRJobsOverviewRow, error)
	GetSystemUsersOverview(ctx context.Context) (GetSystemUsersOverviewRow, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error)
	ListGroupMembershipsByUserID(ctx context.Context, userID pgtype.UUID) ([]ListGroupMembershipsByUserIDRow, error)
	ListRecentAuditLogsByTargetUserID(ctx context.Context, targetUserID pgtype.UUID) ([]ListRecentAuditLogsByTargetUserIDRow, error)
	RevokeRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	RevokeSessionsByUserID(ctx context.Context, arg RevokeSessionsByUserIDParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error)
}

var _ Querier = (*Queries)(nil)
