// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlement.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSettlementMembership = `-- name: GetActiveSettlementMembership :one
SELECT gm.id, gm.user_id, gm.role, u.display_name
FROM group_members gm
JOIN users u ON u.id = gm.user_id
JOIN groups g ON g.id = gm.group_id AND g.status = 'active'
WHERE gm.group_id = $1 AND gm.user_id = $2 AND gm.status = 'active'
`

type GetActiveSettlementMembershipParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

type GetActiveSettlementMembershipRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        interface{} `json:"role"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) GetActiveSettlementMembership(ctx context.Context, arg GetActiveSettlementMembershipParams) (GetActiveSettlementMembershipRow, error) {
	row := q.db.QueryRow(ctx, getActiveSettlementMembership, arg.GroupID, arg.UserID)
	var i GetActiveSettlementMembershipRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
	)
	return i, err
}

const getCallerDebtTotals = `-- name: GetCallerDebtTotals :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE debtor_member_id = $2 AND status IN ('awaiting', 'pending_confirmation')), 0)::bigint AS payable,
    COALESCE(SUM(amount) FILTER (WHERE creditor_member_id = $2 AND status IN ('awaiting', 'pending_confirmation')), 0)::bigint AS receivable
FROM debts WHERE group_id = $1
`

type GetCallerDebtTotalsParams struct {
	GroupID        pgtype.UUID `json:"group_id"`
	DebtorMemberID pgtype.UUID `json:"debtor_member_id"`
}

type GetCallerDebtTotalsRow struct {
	Payable    int64 `json:"payable"`
	Receivable int64 `json:"receivable"`
}

func (q *Queries) GetCallerDebtTotals(ctx context.Context, arg GetCallerDebtTotalsParams) (GetCallerDebtTotalsRow, error) {
	row := q.db.QueryRow(ctx, getCallerDebtTotals, arg.GroupID, arg.DebtorMemberID)
	var i GetCallerDebtTotalsRow
	err := row.Scan(&i.Payable, &i.Receivable)
	return i, err
}

const getDebtMatrix = `-- name: GetDebtMatrix :many
WITH directional AS (
    SELECT debtor_member_id, creditor_member_id, SUM(amount)::bigint AS amount, COUNT(*)::bigint AS debt_count
    FROM debts
    WHERE group_id = $1 AND status IN ('awaiting', 'pending_confirmation')
    GROUP BY debtor_member_id, creditor_member_id
), pairs AS (
    SELECT LEAST(debtor_member_id, creditor_member_id) AS left_id,
           GREATEST(debtor_member_id, creditor_member_id) AS right_id,
           SUM(CASE WHEN debtor_member_id < creditor_member_id THEN amount ELSE -amount END)::bigint AS net,
           SUM(debt_count)::bigint AS debt_count
    FROM directional GROUP BY 1, 2
)
SELECT (CASE WHEN net > 0 THEN left_id ELSE right_id END)::uuid AS debtor_member_id,
       (CASE WHEN net > 0 THEN right_id ELSE left_id END)::uuid AS creditor_member_id,
       abs(net)::bigint AS total_amount,
       debt_count
FROM pairs WHERE net <> 0
ORDER BY debtor_member_id, creditor_member_id
`

type GetDebtMatrixRow struct {
	DebtorMemberID   pgtype.UUID `json:"debtor_member_id"`
	CreditorMemberID pgtype.UUID `json:"creditor_member_id"`
	TotalAmount      int64       `json:"total_amount"`
	DebtCount        int64       `json:"debt_count"`
}

func (q *Queries) GetDebtMatrix(ctx context.Context, groupID pgtype.UUID) ([]GetDebtMatrixRow, error) {
	rows, err := q.db.Query(ctx, getDebtMatrix, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtMatrixRow
	for rows.Next() {
		var i GetDebtMatrixRow
		if err := rows.Scan(
			&i.DebtorMemberID,
			&i.CreditorMemberID,
			&i.TotalAmount,
			&i.DebtCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseSummary = `-- name: GetExpenseSummary :one
SELECT
    COALESCE(SUM(d.amount) FILTER (WHERE d.debtor_member_id = $2 AND d.status IN ('awaiting', 'pending_confirmation')), 0)::bigint AS total_owed,
    COALESCE(SUM(d.amount) FILTER (WHERE d.debtor_member_id = $2 AND d.status = 'settled'), 0)::bigint AS total_settled,
    COALESCE(SUM(d.amount) FILTER (WHERE d.creditor_member_id = $2 AND d.status IN ('awaiting', 'pending_confirmation')), 0)::bigint AS total_receivable,
    COALESCE((SELECT v.net_balance FROM v_member_balances v WHERE v.group_id = $1 AND v.member_id = $2), 0)::bigint AS net_balance
FROM debts d WHERE d.group_id = $1
`

type GetExpenseSummaryParams struct {
	GroupID        pgtype.UUID `json:"group_id"`
	DebtorMemberID pgtype.UUID `json:"debtor_member_id"`
}

type GetExpenseSummaryRow struct {
	TotalOwed       int64 `json:"total_owed"`
	TotalSettled    int64 `json:"total_settled"`
	TotalReceivable int64 `json:"total_receivable"`
	NetBalance      int64 `json:"net_balance"`
}

func (q *Queries) GetExpenseSummary(ctx context.Context, arg GetExpenseSummaryParams) (GetExpenseSummaryRow, error) {
	row := q.db.QueryRow(ctx, getExpenseSummary, arg.GroupID, arg.DebtorMemberID)
	var i GetExpenseSummaryRow
	err := row.Scan(
		&i.TotalOwed,
		&i.TotalSettled,
		&i.TotalReceivable,
		&i.NetBalance,
	)
	return i, err
}

const listDebtRows = `-- name: ListDebtRows :many
SELECT d.id, d.bill_id, b.bill_date, COALESCE(b.merchant_name, '') AS merchant_name,
       d.debtor_member_id, du.display_name AS debtor_display_name, du.avatar_object_key AS debtor_avatar_object_key,
       d.creditor_member_id, cu.display_name AS creditor_display_name, cu.avatar_object_key AS creditor_avatar_object_key,
       d.amount, d.status::text AS status, d.reminder_count, d.last_reminded_at, d.payment_id, d.created_at, d.settled_at
FROM debts d
JOIN bills b ON b.id = d.bill_id AND b.group_id = d.group_id
JOIN group_members dm ON dm.id = d.debtor_member_id
JOIN users du ON du.id = dm.user_id
JOIN group_members cm ON cm.id = d.creditor_member_id
JOIN users cu ON cu.id = cm.user_id
WHERE d.group_id = $1
  AND ($3::uuid IS NULL OR d.debtor_member_id = $3)
  AND ($4::uuid IS NULL OR d.creditor_member_id = $4)
  AND ($5::text IS NULL OR d.status::text = $5)
  AND ($6::timestamptz IS NULL OR d.created_at < $6 OR (d.created_at = $6 AND d.id < $7))
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2
`

type ListDebtRowsParams struct {
	GroupID         pgtype.UUID        `json:"group_id"`
	Limit           int32              `json:"limit"`
	DebtorID        pgtype.UUID        `json:"debtor_id"`
	CreditorID      pgtype.UUID        `json:"creditor_id"`
	Status          pgtype.Text        `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

type ListDebtRowsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BillID                  pgtype.UUID        `json:"bill_id"`
	BillDate                pgtype.Date        `json:"bill_date"`
	MerchantName            string             `json:"merchant_name"`
	DebtorMemberID          pgtype.UUID        `json:"debtor_member_id"`
	DebtorDisplayName       string             `json:"debtor_display_name"`
	DebtorAvatarObjectKey   pgtype.Text        `json:"debtor_avatar_object_key"`
	CreditorMemberID        pgtype.UUID        `json:"creditor_member_id"`
	CreditorDisplayName     string             `json:"creditor_display_name"`
	CreditorAvatarObjectKey pgtype.Text        `json:"creditor_avatar_object_key"`
	Amount                  int64              `json:"amount"`
	Status                  string             `json:"status"`
	ReminderCount           int32              `json:"reminder_count"`
	LastRemindedAt          pgtype.Timestamptz `json:"last_reminded_at"`
	PaymentID               pgtype.UUID        `json:"payment_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SettledAt               pgtype.Timestamptz `json:"settled_at"`
}

func (q *Queries) ListDebtRows(ctx context.Context, arg ListDebtRowsParams) ([]ListDebtRowsRow, error) {
	rows, err := q.db.Query(ctx, listDebtRows,
		arg.GroupID,
		arg.Limit,
		arg.DebtorID,
		arg.CreditorID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebtRowsRow
	for rows.Next() {
		var i ListDebtRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.BillDate,
			&i.MerchantName,
			&i.DebtorMemberID,
			&i.DebtorDisplayName,
			&i.DebtorAvatarObjectKey,
			&i.CreditorMemberID,
			&i.CreditorDisplayName,
			&i.CreditorAvatarObjectKey,
			&i.Amount,
			&i.Status,
			&i.ReminderCount,
			&i.LastRemindedAt,
			&i.PaymentID,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseRows = `-- name: ListExpenseRows :many
WITH page AS (
    SELECT DISTINCT b.id, b.created_at
    FROM bill_item_assignments bia
    JOIN bill_items bi ON bi.id = bia.bill_item_id AND bi.group_id = bia.group_id
    JOIN bills b ON b.id = bi.bill_id AND b.group_id = bi.group_id AND b.status = 'finalized'
    WHERE bia.group_id = $1 AND bia.member_id = $2
      AND ($3::timestamptz IS NULL OR b.created_at < $3 OR (b.created_at = $3 AND b.id < $4))
    ORDER BY b.created_at DESC, b.id DESC
    LIMIT $5
), assignment_totals AS (
    SELECT bill_item_id, SUM(weight) AS total_weight
    FROM bill_item_assignments
    GROUP BY bill_item_id
), raw_item_shares AS (
    SELECT bi.bill_id,
           bi.id AS item_id,
           floor(bi.final_price * bia.weight / at.total_weight)::bigint AS item_base,
           (bi.final_price * bia.weight / at.total_weight)
               - floor(bi.final_price * bia.weight / at.total_weight) AS item_fraction,
           bs.item_subtotal
    FROM page
    JOIN bill_items bi ON bi.bill_id = page.id
    JOIN bill_item_assignments bia
      ON bia.bill_item_id = bi.id AND bia.group_id = bi.group_id AND bia.member_id = $2
    JOIN assignment_totals at ON at.bill_item_id = bia.bill_item_id
    JOIN bill_shares bs ON bs.bill_id = bi.bill_id AND bs.member_id = bia.member_id
), ranked_item_shares AS (
    SELECT bill_id,
           item_id,
           item_base,
           item_subtotal - SUM(item_base) OVER (PARTITION BY bill_id) AS residual,
           ROW_NUMBER() OVER (PARTITION BY bill_id ORDER BY item_fraction DESC, item_id ASC) AS remainder_rank
    FROM raw_item_shares
)
SELECT b.id AS bill_id,
       b.bill_date,
       COALESCE(b.merchant_name, '') AS merchant_name,
       bi.name AS item_name,
       bi.quantity::text AS quantity,
       bi.unit_price,
       bi.line_total,
       bi.discount_amount AS item_discount_amount,
       bi.final_price AS item_final_price,
       (bia.weight / at.total_weight)::text AS share_ratio,
       (ris.item_base + CASE WHEN ris.remainder_rank <= ris.residual THEN 1 ELSE 0 END)::bigint AS item_share,
       bs.service_charge_share,
       bs.vat_share,
       bs.discount_share,
       bs.rounding_adjustment,
       bs.final_amount,
       b.creditor_member_id,
       creditor.display_name AS creditor_display_name,
       d.id AS debt_id,
       COALESCE(d.status::text, '') AS debt_status,
       b.created_at
FROM page
JOIN bills b ON b.id = page.id
JOIN bill_items bi ON bi.bill_id = b.id AND bi.group_id = b.group_id
JOIN bill_item_assignments bia ON bia.bill_item_id = bi.id AND bia.group_id = bi.group_id AND bia.member_id = $2
JOIN assignment_totals at ON at.bill_item_id = bia.bill_item_id
JOIN ranked_item_shares ris ON ris.bill_id = b.id AND ris.item_id = bi.id
JOIN bill_shares bs ON bs.bill_id = b.id AND bs.member_id = bia.member_id
JOIN group_members creditor_member ON creditor_member.id = b.creditor_member_id
JOIN users creditor ON creditor.id = creditor_member.user_id
LEFT JOIN debts d ON d.bill_id = b.id AND d.debtor_member_id = bia.member_id AND d.creditor_member_id = b.creditor_member_id
ORDER BY b.created_at DESC, b.id DESC, bi.position, bi.id
`

type ListExpenseRowsParams struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	MemberID pgtype.UUID        `json:"member_id"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	ID       pgtype.UUID        `json:"id"`
	Limit    int32              `json:"limit"`
}

type ListExpenseRowsRow struct {
	BillID              pgtype.UUID        `json:"bill_id"`
	BillDate            pgtype.Date        `json:"bill_date"`
	MerchantName        string             `json:"merchant_name"`
	ItemName            string             `json:"item_name"`
	Quantity            string             `json:"quantity"`
	UnitPrice           int64              `json:"unit_price"`
	LineTotal           int64              `json:"line_total"`
	ItemDiscountAmount  int64              `json:"item_discount_amount"`
	ItemFinalPrice      int64              `json:"item_final_price"`
	ShareRatio          string             `json:"share_ratio"`
	ItemShare           int64              `json:"item_share"`
	ServiceChargeShare  int64              `json:"service_charge_share"`
	VatShare            int64              `json:"vat_share"`
	DiscountShare       int64              `json:"discount_share"`
	RoundingAdjustment  int64              `json:"rounding_adjustment"`
	FinalAmount         int64              `json:"final_amount"`
	CreditorMemberID    pgtype.UUID        `json:"creditor_member_id"`
	CreditorDisplayName string             `json:"creditor_display_name"`
	DebtID              pgtype.UUID        `json:"debt_id"`
	DebtStatus          interface{}        `json:"debt_status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListExpenseRows(ctx context.Context, arg ListExpenseRowsParams) ([]ListExpenseRowsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseRows,
		arg.GroupID,
		arg.MemberID,
		arg.Column3,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseRowsRow
	for rows.Next() {
		var i ListExpenseRowsRow
		if err := rows.Scan(
			&i.BillID,
			&i.BillDate,
			&i.MerchantName,
			&i.ItemName,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.ItemDiscountAmount,
			&i.ItemFinalPrice,
			&i.ShareRatio,
			&i.ItemShare,
			&i.ServiceChargeShare,
			&i.VatShare,
			&i.DiscountShare,
			&i.RoundingAdjustment,
			&i.FinalAmount,
			&i.CreditorMemberID,
			&i.CreditorDisplayName,
			&i.DebtID,
			&i.DebtStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
