// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settlement.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSettlementMembership = `-- name: GetActiveSettlementMembership :one
SELECT gm.id, gm.user_id, gm.role, u.display_name
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1 AND gm.user_id = $2 AND gm.status = 'active'
`

type GetActiveSettlementMembershipParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

type GetActiveSettlementMembershipRow struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Role        interface{} `json:"role"`
	DisplayName string      `json:"display_name"`
}

func (q *Queries) GetActiveSettlementMembership(ctx context.Context, arg GetActiveSettlementMembershipParams) (GetActiveSettlementMembershipRow, error) {
	row := q.db.QueryRow(ctx, getActiveSettlementMembership, arg.GroupID, arg.UserID)
	var i GetActiveSettlementMembershipRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.DisplayName,
	)
	return i, err
}

const getCallerDebtTotals = `-- name: GetCallerDebtTotals :one
SELECT
    COALESCE(SUM(amount) FILTER (WHERE debtor_member_id = $2 AND status NOT IN ('settled', 'voided')), 0)::bigint AS payable,
    COALESCE(SUM(amount) FILTER (WHERE creditor_member_id = $2 AND status NOT IN ('settled', 'voided')), 0)::bigint AS receivable
FROM debts WHERE group_id = $1
`

type GetCallerDebtTotalsParams struct {
	GroupID        pgtype.UUID `json:"group_id"`
	DebtorMemberID pgtype.UUID `json:"debtor_member_id"`
}

type GetCallerDebtTotalsRow struct {
	Payable    int64 `json:"payable"`
	Receivable int64 `json:"receivable"`
}

func (q *Queries) GetCallerDebtTotals(ctx context.Context, arg GetCallerDebtTotalsParams) (GetCallerDebtTotalsRow, error) {
	row := q.db.QueryRow(ctx, getCallerDebtTotals, arg.GroupID, arg.DebtorMemberID)
	var i GetCallerDebtTotalsRow
	err := row.Scan(&i.Payable, &i.Receivable)
	return i, err
}

const getDebtMatrix = `-- name: GetDebtMatrix :many
WITH directional AS (
    SELECT debtor_member_id, creditor_member_id, SUM(amount)::bigint AS amount, COUNT(*)::bigint AS debt_count
    FROM debts
    WHERE group_id = $1 AND status NOT IN ('settled', 'voided')
    GROUP BY debtor_member_id, creditor_member_id
), pairs AS (
    SELECT LEAST(debtor_member_id, creditor_member_id) AS left_id,
           GREATEST(debtor_member_id, creditor_member_id) AS right_id,
           SUM(CASE WHEN debtor_member_id < creditor_member_id THEN amount ELSE -amount END)::bigint AS net,
           SUM(debt_count)::bigint AS debt_count
    FROM directional GROUP BY 1, 2
)
SELECT (CASE WHEN net > 0 THEN left_id ELSE right_id END)::uuid AS debtor_member_id,
       (CASE WHEN net > 0 THEN right_id ELSE left_id END)::uuid AS creditor_member_id,
       abs(net)::bigint AS total_amount,
       debt_count
FROM pairs WHERE net <> 0
ORDER BY debtor_member_id, creditor_member_id
`

type GetDebtMatrixRow struct {
	DebtorMemberID   pgtype.UUID `json:"debtor_member_id"`
	CreditorMemberID pgtype.UUID `json:"creditor_member_id"`
	TotalAmount      int64       `json:"total_amount"`
	DebtCount        int64       `json:"debt_count"`
}

func (q *Queries) GetDebtMatrix(ctx context.Context, groupID pgtype.UUID) ([]GetDebtMatrixRow, error) {
	rows, err := q.db.Query(ctx, getDebtMatrix, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtMatrixRow
	for rows.Next() {
		var i GetDebtMatrixRow
		if err := rows.Scan(
			&i.DebtorMemberID,
			&i.CreditorMemberID,
			&i.TotalAmount,
			&i.DebtCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseSummary = `-- name: GetExpenseSummary :one
SELECT
    COALESCE(SUM(d.amount) FILTER (WHERE d.debtor_member_id = $2 AND d.status NOT IN ('settled', 'voided')), 0)::bigint AS total_owed,
    COALESCE(SUM(d.amount) FILTER (WHERE d.debtor_member_id = $2 AND d.status = 'settled'), 0)::bigint AS total_settled,
    COALESCE(SUM(d.amount) FILTER (WHERE d.creditor_member_id = $2 AND d.status NOT IN ('settled', 'voided')), 0)::bigint AS total_receivable,
    COALESCE((SELECT v.net_balance FROM v_member_balances v WHERE v.group_id = $1 AND v.member_id = $2), 0)::bigint AS net_balance
FROM debts d WHERE d.group_id = $1
`

type GetExpenseSummaryParams struct {
	GroupID        pgtype.UUID `json:"group_id"`
	DebtorMemberID pgtype.UUID `json:"debtor_member_id"`
}

type GetExpenseSummaryRow struct {
	TotalOwed       int64 `json:"total_owed"`
	TotalSettled    int64 `json:"total_settled"`
	TotalReceivable int64 `json:"total_receivable"`
	NetBalance      int64 `json:"net_balance"`
}

func (q *Queries) GetExpenseSummary(ctx context.Context, arg GetExpenseSummaryParams) (GetExpenseSummaryRow, error) {
	row := q.db.QueryRow(ctx, getExpenseSummary, arg.GroupID, arg.DebtorMemberID)
	var i GetExpenseSummaryRow
	err := row.Scan(
		&i.TotalOwed,
		&i.TotalSettled,
		&i.TotalReceivable,
		&i.NetBalance,
	)
	return i, err
}

const getPaymentRow = `-- name: GetPaymentRow :one
SELECT p.id, p.group_id, p.debtor_member_id, p.creditor_member_id, p.amount, p.reference_code, p.qr_payload, p.image_object_key, p.note, p.rejection_reason, p.created_at, p.submitted_at, p.confirmed_at, p.rejected_at, p.updated_at, p.status, p.recipient_bank_code, p.recipient_bank_name, p.recipient_account_number, p.recipient_account_holder, p.stalled_alerted_at, debtor.user_id AS debtor_user_id, creditor.user_id AS creditor_user_id,
       creditor_user.default_bank_code, creditor_user.default_bank_account_number,
       creditor_user.default_bank_account_holder
FROM payments p
JOIN group_members debtor ON debtor.id = p.debtor_member_id AND debtor.group_id = p.group_id
JOIN group_members creditor ON creditor.id = p.creditor_member_id AND creditor.group_id = p.group_id
JOIN users creditor_user ON creditor_user.id = creditor.user_id
WHERE p.id = $1 AND p.group_id = $2
`

type GetPaymentRowParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

type GetPaymentRowRow struct {
	ID                       pgtype.UUID        `json:"id"`
	GroupID                  pgtype.UUID        `json:"group_id"`
	DebtorMemberID           pgtype.UUID        `json:"debtor_member_id"`
	CreditorMemberID         pgtype.UUID        `json:"creditor_member_id"`
	Amount                   int64              `json:"amount"`
	ReferenceCode            string             `json:"reference_code"`
	QrPayload                pgtype.Text        `json:"qr_payload"`
	ImageObjectKey           pgtype.Text        `json:"image_object_key"`
	Note                     pgtype.Text        `json:"note"`
	RejectionReason          pgtype.Text        `json:"rejection_reason"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	SubmittedAt              pgtype.Timestamptz `json:"submitted_at"`
	ConfirmedAt              pgtype.Timestamptz `json:"confirmed_at"`
	RejectedAt               pgtype.Timestamptz `json:"rejected_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	Status                   interface{}        `json:"status"`
	RecipientBankCode        pgtype.Text        `json:"recipient_bank_code"`
	RecipientBankName        pgtype.Text        `json:"recipient_bank_name"`
	RecipientAccountNumber   pgtype.Text        `json:"recipient_account_number"`
	RecipientAccountHolder   pgtype.Text        `json:"recipient_account_holder"`
	StalledAlertedAt         pgtype.Timestamptz `json:"stalled_alerted_at"`
	DebtorUserID             pgtype.UUID        `json:"debtor_user_id"`
	CreditorUserID           pgtype.UUID        `json:"creditor_user_id"`
	DefaultBankCode          pgtype.Text        `json:"default_bank_code"`
	DefaultBankAccountNumber pgtype.Text        `json:"default_bank_account_number"`
	DefaultBankAccountHolder pgtype.Text        `json:"default_bank_account_holder"`
}

func (q *Queries) GetPaymentRow(ctx context.Context, arg GetPaymentRowParams) (GetPaymentRowRow, error) {
	row := q.db.QueryRow(ctx, getPaymentRow, arg.ID, arg.GroupID)
	var i GetPaymentRowRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.DebtorMemberID,
		&i.CreditorMemberID,
		&i.Amount,
		&i.ReferenceCode,
		&i.QrPayload,
		&i.ImageObjectKey,
		&i.Note,
		&i.RejectionReason,
		&i.CreatedAt,
		&i.SubmittedAt,
		&i.ConfirmedAt,
		&i.RejectedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.RecipientBankCode,
		&i.RecipientBankName,
		&i.RecipientAccountNumber,
		&i.RecipientAccountHolder,
		&i.StalledAlertedAt,
		&i.DebtorUserID,
		&i.CreditorUserID,
		&i.DefaultBankCode,
		&i.DefaultBankAccountNumber,
		&i.DefaultBankAccountHolder,
	)
	return i, err
}

const listAutomatedReminderCandidates = `-- name: ListAutomatedReminderCandidates :many
SELECT id, group_id FROM debts
WHERE status = 'awaiting' AND created_at <= $1 AND reminder_count < $2
ORDER BY id LIMIT 100
`

type ListAutomatedReminderCandidatesParams struct {
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ReminderCount int32              `json:"reminder_count"`
}

type ListAutomatedReminderCandidatesRow struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) ListAutomatedReminderCandidates(ctx context.Context, arg ListAutomatedReminderCandidatesParams) ([]ListAutomatedReminderCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAutomatedReminderCandidates, arg.CreatedAt, arg.ReminderCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutomatedReminderCandidatesRow
	for rows.Next() {
		var i ListAutomatedReminderCandidatesRow
		if err := rows.Scan(&i.ID, &i.GroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtRows = `-- name: ListDebtRows :many
SELECT d.id, d.bill_id, b.bill_date, COALESCE(b.merchant_name, '') AS merchant_name,
       d.debtor_member_id, du.display_name AS debtor_display_name, du.avatar_object_key AS debtor_avatar_object_key,
       d.creditor_member_id, cu.display_name AS creditor_display_name, cu.avatar_object_key AS creditor_avatar_object_key,
       d.amount, d.status::text AS status, d.reminder_count, d.payment_id, d.created_at, d.settled_at
FROM debts d
JOIN bills b ON b.id = d.bill_id AND b.group_id = d.group_id
JOIN group_members dm ON dm.id = d.debtor_member_id
JOIN users du ON du.id = dm.user_id
JOIN group_members cm ON cm.id = d.creditor_member_id
JOIN users cu ON cu.id = cm.user_id
WHERE d.group_id = $1
  AND ($3::uuid IS NULL OR d.debtor_member_id = $3)
  AND ($4::uuid IS NULL OR d.creditor_member_id = $4)
  AND ($5::text IS NULL OR d.status::text = $5)
  AND ($6::timestamptz IS NULL OR d.created_at < $6 OR (d.created_at = $6 AND d.id < $7))
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2
`

type ListDebtRowsParams struct {
	GroupID         pgtype.UUID        `json:"group_id"`
	Limit           int32              `json:"limit"`
	DebtorID        pgtype.UUID        `json:"debtor_id"`
	CreditorID      pgtype.UUID        `json:"creditor_id"`
	Status          pgtype.Text        `json:"status"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
}

type ListDebtRowsRow struct {
	ID                      pgtype.UUID        `json:"id"`
	BillID                  pgtype.UUID        `json:"bill_id"`
	BillDate                pgtype.Date        `json:"bill_date"`
	MerchantName            string             `json:"merchant_name"`
	DebtorMemberID          pgtype.UUID        `json:"debtor_member_id"`
	DebtorDisplayName       string             `json:"debtor_display_name"`
	DebtorAvatarObjectKey   pgtype.Text        `json:"debtor_avatar_object_key"`
	CreditorMemberID        pgtype.UUID        `json:"creditor_member_id"`
	CreditorDisplayName     string             `json:"creditor_display_name"`
	CreditorAvatarObjectKey pgtype.Text        `json:"creditor_avatar_object_key"`
	Amount                  int64              `json:"amount"`
	Status                  string             `json:"status"`
	ReminderCount           int32              `json:"reminder_count"`
	PaymentID               pgtype.UUID        `json:"payment_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	SettledAt               pgtype.Timestamptz `json:"settled_at"`
}

func (q *Queries) ListDebtRows(ctx context.Context, arg ListDebtRowsParams) ([]ListDebtRowsRow, error) {
	rows, err := q.db.Query(ctx, listDebtRows,
		arg.GroupID,
		arg.Limit,
		arg.DebtorID,
		arg.CreditorID,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebtRowsRow
	for rows.Next() {
		var i ListDebtRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.BillDate,
			&i.MerchantName,
			&i.DebtorMemberID,
			&i.DebtorDisplayName,
			&i.DebtorAvatarObjectKey,
			&i.CreditorMemberID,
			&i.CreditorDisplayName,
			&i.CreditorAvatarObjectKey,
			&i.Amount,
			&i.Status,
			&i.ReminderCount,
			&i.PaymentID,
			&i.CreatedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseRows = `-- name: ListExpenseRows :many
WITH page AS (
    SELECT DISTINCT b.id, b.created_at
    FROM bill_item_assignments bia
    JOIN bill_items bi ON bi.id = bia.bill_item_id AND bi.group_id = bia.group_id
    JOIN bills b ON b.id = bi.bill_id AND b.group_id = bi.group_id AND b.status = 'finalized'
    WHERE bia.group_id = $1 AND bia.member_id = $2
      AND ($3::timestamptz IS NULL OR b.created_at < $3 OR (b.created_at = $3 AND b.id < $4))
    ORDER BY b.created_at DESC, b.id DESC
    LIMIT $5
), assignment_totals AS (
    SELECT bill_item_id, SUM(weight) AS total_weight
    FROM bill_item_assignments
    GROUP BY bill_item_id
)
SELECT b.id AS bill_id,
       b.bill_date,
       COALESCE(b.merchant_name, '') AS merchant_name,
       bi.name AS item_name,
       bi.quantity::text AS quantity,
       bi.unit_price,
       bi.line_total,
       bi.discount_amount AS item_discount_amount,
       bi.final_price AS item_final_price,
       (bia.weight / at.total_weight)::text AS share_ratio,
       floor(bi.final_price * bia.weight / at.total_weight)::bigint AS item_share,
       bs.service_charge_share,
       bs.vat_share,
       bs.discount_share,
       bs.rounding_adjustment,
       bs.final_amount,
       b.creditor_member_id,
       creditor.display_name AS creditor_display_name,
       d.id AS debt_id,
       COALESCE(d.status::text, '') AS debt_status,
       b.created_at
FROM page
JOIN bills b ON b.id = page.id
JOIN bill_items bi ON bi.bill_id = b.id AND bi.group_id = b.group_id
JOIN bill_item_assignments bia ON bia.bill_item_id = bi.id AND bia.group_id = bi.group_id AND bia.member_id = $2
JOIN assignment_totals at ON at.bill_item_id = bia.bill_item_id
JOIN bill_shares bs ON bs.bill_id = b.id AND bs.member_id = bia.member_id
JOIN group_members creditor_member ON creditor_member.id = b.creditor_member_id
JOIN users creditor ON creditor.id = creditor_member.user_id
LEFT JOIN debts d ON d.bill_id = b.id AND d.debtor_member_id = bia.member_id AND d.creditor_member_id = b.creditor_member_id
ORDER BY b.created_at DESC, b.id DESC, bi.position, bi.id
`

type ListExpenseRowsParams struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	MemberID pgtype.UUID        `json:"member_id"`
	Column3  pgtype.Timestamptz `json:"column_3"`
	ID       pgtype.UUID        `json:"id"`
	Limit    int32              `json:"limit"`
}

type ListExpenseRowsRow struct {
	BillID              pgtype.UUID        `json:"bill_id"`
	BillDate            pgtype.Date        `json:"bill_date"`
	MerchantName        string             `json:"merchant_name"`
	ItemName            string             `json:"item_name"`
	Quantity            string             `json:"quantity"`
	UnitPrice           int64              `json:"unit_price"`
	LineTotal           int64              `json:"line_total"`
	ItemDiscountAmount  int64              `json:"item_discount_amount"`
	ItemFinalPrice      int64              `json:"item_final_price"`
	ShareRatio          string             `json:"share_ratio"`
	ItemShare           int64              `json:"item_share"`
	ServiceChargeShare  int64              `json:"service_charge_share"`
	VatShare            int64              `json:"vat_share"`
	DiscountShare       int64              `json:"discount_share"`
	RoundingAdjustment  int64              `json:"rounding_adjustment"`
	FinalAmount         int64              `json:"final_amount"`
	CreditorMemberID    pgtype.UUID        `json:"creditor_member_id"`
	CreditorDisplayName string             `json:"creditor_display_name"`
	DebtID              pgtype.UUID        `json:"debt_id"`
	DebtStatus          interface{}        `json:"debt_status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListExpenseRows(ctx context.Context, arg ListExpenseRowsParams) ([]ListExpenseRowsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseRows,
		arg.GroupID,
		arg.MemberID,
		arg.Column3,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseRowsRow
	for rows.Next() {
		var i ListExpenseRowsRow
		if err := rows.Scan(
			&i.BillID,
			&i.BillDate,
			&i.MerchantName,
			&i.ItemName,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.ItemDiscountAmount,
			&i.ItemFinalPrice,
			&i.ShareRatio,
			&i.ItemShare,
			&i.ServiceChargeShare,
			&i.VatShare,
			&i.DiscountShare,
			&i.RoundingAdjustment,
			&i.FinalAmount,
			&i.CreditorMemberID,
			&i.CreditorDisplayName,
			&i.DebtID,
			&i.DebtStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentDebtIDs = `-- name: ListPaymentDebtIDs :many
SELECT debt_id FROM payment_debts WHERE payment_id = $1 ORDER BY debt_id
`

func (q *Queries) ListPaymentDebtIDs(ctx context.Context, paymentID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listPaymentDebtIDs, paymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var debt_id pgtype.UUID
		if err := rows.Scan(&debt_id); err != nil {
			return nil, err
		}
		items = append(items, debt_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalledPaymentCandidates = `-- name: ListStalledPaymentCandidates :many
SELECT id, group_id FROM payments
WHERE status = 'pending_confirmation' AND submitted_at <= $1
ORDER BY id LIMIT 100
`

type ListStalledPaymentCandidatesRow struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) ListStalledPaymentCandidates(ctx context.Context, submittedAt pgtype.Timestamptz) ([]ListStalledPaymentCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listStalledPaymentCandidates, submittedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStalledPaymentCandidatesRow
	for rows.Next() {
		var i ListStalledPaymentCandidatesRow
		if err := rows.Scan(&i.ID, &i.GroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
