// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bill_close.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const captureOpenBills = `-- name: CaptureOpenBills :many
SELECT id, version, (status = 'reviewed') AS captured_reviewed
FROM bills
WHERE group_id = $1 AND status IN ('draft', 'reviewed')
ORDER BY id
`

type CaptureOpenBillsRow struct {
	ID               pgtype.UUID `json:"id"`
	Version          int32       `json:"version"`
	CapturedReviewed bool        `json:"captured_reviewed"`
}

func (q *Queries) CaptureOpenBills(ctx context.Context, groupID pgtype.UUID) ([]CaptureOpenBillsRow, error) {
	rows, err := q.db.Query(ctx, captureOpenBills, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CaptureOpenBillsRow
	for rows.Next() {
		var i CaptureOpenBillsRow
		if err := rows.Scan(&i.ID, &i.Version, &i.CapturedReviewed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearGroupSubmissionLockedAt = `-- name: ClearGroupSubmissionLockedAt :one
UPDATE groups
SET bill_submission_locked_at = NULL
WHERE id = $1 AND status = 'active'
RETURNING bill_submission_locked_at
`

func (q *Queries) ClearGroupSubmissionLockedAt(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, clearGroupSubmissionLockedAt, id)
	var bill_submission_locked_at pgtype.Timestamptz
	err := row.Scan(&bill_submission_locked_at)
	return bill_submission_locked_at, err
}

const completeFinalizeBatch = `-- name: CompleteFinalizeBatch :execrows
UPDATE group_bill_finalize_batches
SET status = 'completed',
    finalized_count = $2,
    failed_count = $3,
    started_at = COALESCE(started_at, now()),
    completed_at = now(),
    updated_at = now()
WHERE id = $1 AND status IN ('queued', 'processing')
  AND finalized_count + failed_count = $4
`

type CompleteFinalizeBatchParams struct {
	ID               pgtype.UUID `json:"id"`
	FinalizedCount   int32       `json:"finalized_count"`
	FailedCount      int32       `json:"failed_count"`
	FinalizedCount_2 int32       `json:"finalized_count_2"`
}

func (q *Queries) CompleteFinalizeBatch(ctx context.Context, arg CompleteFinalizeBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeFinalizeBatch,
		arg.ID,
		arg.FinalizedCount,
		arg.FailedCount,
		arg.FinalizedCount_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveBatchesForGroup = `-- name: CountActiveBatchesForGroup :one
SELECT count(*) FROM group_bill_finalize_batches
WHERE group_id = $1 AND status IN ('queued', 'processing')
`

func (q *Queries) CountActiveBatchesForGroup(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBatchesForGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingBatchItems = `-- name: CountPendingBatchItems :one
SELECT count(*) FROM group_bill_finalize_items
WHERE batch_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingBatchItems(ctx context.Context, batchID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingBatchItems, batchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getActiveCaptainMembership = `-- name: GetActiveCaptainMembership :one
SELECT id, group_id, user_id, role, status, joined_at, left_at
FROM group_members gm
WHERE group_id = $1 AND status = 'active' AND role = 'captain'
  AND EXISTS (SELECT 1 FROM groups g WHERE g.id = gm.group_id AND g.status = 'active')
`

func (q *Queries) GetActiveCaptainMembership(ctx context.Context, groupID pgtype.UUID) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getActiveCaptainMembership, groupID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getActiveFinalizeBatch = `-- name: GetActiveFinalizeBatch :many
SELECT id, group_id, requested_by_member_id, status, target_count, finalized_count, failed_count, created_at, updated_at, started_at, completed_at FROM group_bill_finalize_batches
WHERE group_id = $1 AND status IN ('queued', 'processing')
ORDER BY created_at ASC
`

func (q *Queries) GetActiveFinalizeBatch(ctx context.Context, groupID pgtype.UUID) ([]GroupBillFinalizeBatch, error) {
	rows, err := q.db.Query(ctx, getActiveFinalizeBatch, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupBillFinalizeBatch
	for rows.Next() {
		var i GroupBillFinalizeBatch
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.RequestedByMemberID,
			&i.Status,
			&i.TargetCount,
			&i.FinalizedCount,
			&i.FailedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBillStateForBatch = `-- name: GetBillStateForBatch :one


SELECT id, group_id, creditor_member_id, status, version
FROM bills
WHERE id = $1 AND group_id = $2
FOR UPDATE
`

type GetBillStateForBatchParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

type GetBillStateForBatchRow struct {
	ID               pgtype.UUID `json:"id"`
	GroupID          pgtype.UUID `json:"group_id"`
	CreditorMemberID pgtype.UUID `json:"creditor_member_id"`
	Status           interface{} `json:"status"`
	Version          int32       `json:"version"`
}

// Rào chắn archive với batch đang chạy được kiểm tra trong code (DisbandGroup
// của module group) ngay sau khi giữ khóa nhóm, không dùng trigger.
// ============================================================================
// BATCH ITEM WORKER SUPPORT (đọc trong transaction của item)
// ============================================================================
func (q *Queries) GetBillStateForBatch(ctx context.Context, arg GetBillStateForBatchParams) (GetBillStateForBatchRow, error) {
	row := q.db.QueryRow(ctx, getBillStateForBatch, arg.ID, arg.GroupID)
	var i GetBillStateForBatchRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreditorMemberID,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const getFinalizeBatchByID = `-- name: GetFinalizeBatchByID :one
SELECT id, group_id, requested_by_member_id, status, target_count, finalized_count, failed_count, created_at, updated_at, started_at, completed_at FROM group_bill_finalize_batches
WHERE id = $1 AND group_id = $2
`

type GetFinalizeBatchByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetFinalizeBatchByID(ctx context.Context, arg GetFinalizeBatchByIDParams) (GroupBillFinalizeBatch, error) {
	row := q.db.QueryRow(ctx, getFinalizeBatchByID, arg.ID, arg.GroupID)
	var i GroupBillFinalizeBatch
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequestedByMemberID,
		&i.Status,
		&i.TargetCount,
		&i.FinalizedCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getGroupSubmissionLock = `-- name: GetGroupSubmissionLock :one

SELECT bill_submission_locked_at FROM groups
WHERE id = $1 AND status = 'active'
`

// ============================================================================
// GROUP BILL CLOSE V1 (Spec 0008)
// Khóa gửi hóa đơn một chiều, batch chốt toàn bộ và item xử lý từng bill.
// ============================================================================
func (q *Queries) GetGroupSubmissionLock(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getGroupSubmissionLock, id)
	var bill_submission_locked_at pgtype.Timestamptz
	err := row.Scan(&bill_submission_locked_at)
	return bill_submission_locked_at, err
}

const getLatestFinalizeBatch = `-- name: GetLatestFinalizeBatch :one
SELECT id, group_id, requested_by_member_id, status, target_count, finalized_count, failed_count, created_at, updated_at, started_at, completed_at FROM group_bill_finalize_batches
WHERE id = (
    SELECT b.id FROM group_bill_finalize_batches b
    WHERE b.group_id = $1
    ORDER BY b.created_at DESC, b.id DESC
    LIMIT 1
)
`

func (q *Queries) GetLatestFinalizeBatch(ctx context.Context, groupID pgtype.UUID) (GroupBillFinalizeBatch, error) {
	row := q.db.QueryRow(ctx, getLatestFinalizeBatch, groupID)
	var i GroupBillFinalizeBatch
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequestedByMemberID,
		&i.Status,
		&i.TargetCount,
		&i.FinalizedCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const incrementBatchFailedCount = `-- name: IncrementBatchFailedCount :execrows
UPDATE group_bill_finalize_batches
SET failed_count = failed_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementBatchFailedCount(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementBatchFailedCount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementBatchFinalizedCount = `-- name: IncrementBatchFinalizedCount :execrows
UPDATE group_bill_finalize_batches
SET finalized_count = finalized_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementBatchFinalizedCount(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incrementBatchFinalizedCount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertFinalizeBatch = `-- name: InsertFinalizeBatch :one
INSERT INTO group_bill_finalize_batches (
    id, group_id, requested_by_member_id, status,
    target_count, finalized_count, failed_count,
    created_at, updated_at, started_at, completed_at
) VALUES (
    $1, $2, $3, $4, $5, 0, 0, now(), now(), $6, $7
) RETURNING id, group_id, requested_by_member_id, status, target_count, finalized_count, failed_count, created_at, updated_at, started_at, completed_at
`

type InsertFinalizeBatchParams struct {
	ID                  pgtype.UUID        `json:"id"`
	GroupID             pgtype.UUID        `json:"group_id"`
	RequestedByMemberID pgtype.UUID        `json:"requested_by_member_id"`
	Status              interface{}        `json:"status"`
	TargetCount         int32              `json:"target_count"`
	StartedAt           pgtype.Timestamptz `json:"started_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) InsertFinalizeBatch(ctx context.Context, arg InsertFinalizeBatchParams) (GroupBillFinalizeBatch, error) {
	row := q.db.QueryRow(ctx, insertFinalizeBatch,
		arg.ID,
		arg.GroupID,
		arg.RequestedByMemberID,
		arg.Status,
		arg.TargetCount,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i GroupBillFinalizeBatch
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequestedByMemberID,
		&i.Status,
		&i.TargetCount,
		&i.FinalizedCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertFinalizeItem = `-- name: InsertFinalizeItem :execrows
INSERT INTO group_bill_finalize_items (
    batch_id, bill_id, bill_version, captured_reviewed, status,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, 'pending', now(), now()
)
`

type InsertFinalizeItemParams struct {
	BatchID          pgtype.UUID `json:"batch_id"`
	BillID           pgtype.UUID `json:"bill_id"`
	BillVersion      int32       `json:"bill_version"`
	CapturedReviewed bool        `json:"captured_reviewed"`
}

func (q *Queries) InsertFinalizeItem(ctx context.Context, arg InsertFinalizeItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertFinalizeItem,
		arg.BatchID,
		arg.BillID,
		arg.BillVersion,
		arg.CapturedReviewed,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBatchItemsPage = `-- name: ListBatchItemsPage :many
SELECT i.bill_id, i.bill_version, i.captured_reviewed, i.status,
       i.error_code, i.processed_at, i.created_at,
       b.merchant_name AS bill_display_name
FROM group_bill_finalize_items i
LEFT JOIN bills b ON b.id = i.bill_id
WHERE i.batch_id = $1
  AND (
    $2::timestamptz IS NULL
    OR i.created_at > $2
    OR (i.created_at = $2 AND i.bill_id > $3::uuid)
  )
ORDER BY i.created_at ASC, i.bill_id ASC
LIMIT $4
`

type ListBatchItemsPageParams struct {
	BatchID pgtype.UUID        `json:"batch_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.UUID        `json:"column_3"`
	Limit   int32              `json:"limit"`
}

type ListBatchItemsPageRow struct {
	BillID           pgtype.UUID        `json:"bill_id"`
	BillVersion      int32              `json:"bill_version"`
	CapturedReviewed bool               `json:"captured_reviewed"`
	Status           interface{}        `json:"status"`
	ErrorCode        pgtype.Text        `json:"error_code"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	BillDisplayName  pgtype.Text        `json:"bill_display_name"`
}

func (q *Queries) ListBatchItemsPage(ctx context.Context, arg ListBatchItemsPageParams) ([]ListBatchItemsPageRow, error) {
	rows, err := q.db.Query(ctx, listBatchItemsPage,
		arg.BatchID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchItemsPageRow
	for rows.Next() {
		var i ListBatchItemsPageRow
		if err := rows.Scan(
			&i.BillID,
			&i.BillVersion,
			&i.CapturedReviewed,
			&i.Status,
			&i.ErrorCode,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.BillDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBatchItemForUpdate = `-- name: LockBatchItemForUpdate :one
SELECT batch_id, bill_id, bill_version, captured_reviewed, status, error_code, processed_at, created_at, updated_at FROM group_bill_finalize_items
WHERE batch_id = $1 AND bill_id = $2
FOR UPDATE
`

type LockBatchItemForUpdateParams struct {
	BatchID pgtype.UUID `json:"batch_id"`
	BillID  pgtype.UUID `json:"bill_id"`
}

func (q *Queries) LockBatchItemForUpdate(ctx context.Context, arg LockBatchItemForUpdateParams) (GroupBillFinalizeItem, error) {
	row := q.db.QueryRow(ctx, lockBatchItemForUpdate, arg.BatchID, arg.BillID)
	var i GroupBillFinalizeItem
	err := row.Scan(
		&i.BatchID,
		&i.BillID,
		&i.BillVersion,
		&i.CapturedReviewed,
		&i.Status,
		&i.ErrorCode,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockBatchRowForUpdate = `-- name: LockBatchRowForUpdate :one
SELECT id, group_id, requested_by_member_id, status, target_count, finalized_count, failed_count, created_at, updated_at, started_at, completed_at FROM group_bill_finalize_batches
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockBatchRowForUpdate(ctx context.Context, id pgtype.UUID) (GroupBillFinalizeBatch, error) {
	row := q.db.QueryRow(ctx, lockBatchRowForUpdate, id)
	var i GroupBillFinalizeBatch
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.RequestedByMemberID,
		&i.Status,
		&i.TargetCount,
		&i.FinalizedCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markBatchItemFailed = `-- name: MarkBatchItemFailed :execrows
UPDATE group_bill_finalize_items
SET status = 'failed', error_code = $3, processed_at = now(), updated_at = now()
WHERE batch_id = $1 AND bill_id = $2 AND status = 'pending'
`

type MarkBatchItemFailedParams struct {
	BatchID   pgtype.UUID `json:"batch_id"`
	BillID    pgtype.UUID `json:"bill_id"`
	ErrorCode pgtype.Text `json:"error_code"`
}

func (q *Queries) MarkBatchItemFailed(ctx context.Context, arg MarkBatchItemFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBatchItemFailed, arg.BatchID, arg.BillID, arg.ErrorCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markBatchItemFinalized = `-- name: MarkBatchItemFinalized :execrows
UPDATE group_bill_finalize_items
SET status = 'finalized', error_code = NULL, processed_at = now(), updated_at = now()
WHERE batch_id = $1 AND bill_id = $2 AND status = 'pending'
`

type MarkBatchItemFinalizedParams struct {
	BatchID pgtype.UUID `json:"batch_id"`
	BillID  pgtype.UUID `json:"bill_id"`
}

func (q *Queries) MarkBatchItemFinalized(ctx context.Context, arg MarkBatchItemFinalizedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markBatchItemFinalized, arg.BatchID, arg.BillID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteBatchToProcessing = `-- name: PromoteBatchToProcessing :execrows
UPDATE group_bill_finalize_batches
SET status = 'processing', started_at = now(), updated_at = now()
WHERE id = $1 AND status = 'queued'
`

func (q *Queries) PromoteBatchToProcessing(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, promoteBatchToProcessing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGroupSubmissionLockedAt = `-- name: SetGroupSubmissionLockedAt :one
UPDATE groups
SET bill_submission_locked_at = COALESCE(bill_submission_locked_at, now())
WHERE id = $1 AND status = 'active'
RETURNING bill_submission_locked_at
`

func (q *Queries) SetGroupSubmissionLockedAt(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, setGroupSubmissionLockedAt, id)
	var bill_submission_locked_at pgtype.Timestamptz
	err := row.Scan(&bill_submission_locked_at)
	return bill_submission_locked_at, err
}
