// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bill.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countManualOCRAttemptsInWindow = `-- name: CountManualOCRAttemptsInWindow :one
SELECT COUNT(*) FROM ocr_jobs
WHERE bill_id = $1 AND created_at >= $2
`

type CountManualOCRAttemptsInWindowParams struct {
	BillID    pgtype.UUID        `json:"bill_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountManualOCRAttemptsInWindow(ctx context.Context, arg CountManualOCRAttemptsInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countManualOCRAttemptsInWindow, arg.BillID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBill = `-- name: CreateBill :one
INSERT INTO bills (
    id,
    group_id,
    creditor_member_id,
    status,
    merchant_name,
    bill_date,
    subtotal,
    service_charge,
    vat,
    discount,
    total,
    split_method,
    mismatch_codes,
    replaces_bill_id,
    version,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, 1, now(), now()
) RETURNING id, group_id, creditor_member_id, status, merchant_name, bill_date, image_object_key, subtotal, service_charge, vat, discount, total, mismatch_warning, version, created_at, finalized_at, updated_at, replaces_bill_id, voided_at, split_method, mismatch_codes
`

type CreateBillParams struct {
	ID               pgtype.UUID `json:"id"`
	GroupID          pgtype.UUID `json:"group_id"`
	CreditorMemberID pgtype.UUID `json:"creditor_member_id"`
	Status           interface{} `json:"status"`
	MerchantName     pgtype.Text `json:"merchant_name"`
	BillDate         pgtype.Date `json:"bill_date"`
	Subtotal         int64       `json:"subtotal"`
	ServiceCharge    int64       `json:"service_charge"`
	Vat              int64       `json:"vat"`
	Discount         int64       `json:"discount"`
	Total            int64       `json:"total"`
	SplitMethod      string      `json:"split_method"`
	MismatchCodes    []string    `json:"mismatch_codes"`
	ReplacesBillID   pgtype.UUID `json:"replaces_bill_id"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.ID,
		arg.GroupID,
		arg.CreditorMemberID,
		arg.Status,
		arg.MerchantName,
		arg.BillDate,
		arg.Subtotal,
		arg.ServiceCharge,
		arg.Vat,
		arg.Discount,
		arg.Total,
		arg.SplitMethod,
		arg.MismatchCodes,
		arg.ReplacesBillID,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreditorMemberID,
		&i.Status,
		&i.MerchantName,
		&i.BillDate,
		&i.ImageObjectKey,
		&i.Subtotal,
		&i.ServiceCharge,
		&i.Vat,
		&i.Discount,
		&i.Total,
		&i.MismatchWarning,
		&i.Version,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UpdatedAt,
		&i.ReplacesBillID,
		&i.VoidedAt,
		&i.SplitMethod,
		&i.MismatchCodes,
	)
	return i, err
}

const createBillImage = `-- name: CreateBillImage :one

INSERT INTO bill_images (
    id,
    bill_id,
    group_id,
    image_key,
    position,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, now()
) RETURNING id, bill_id, group_id, image_key, position, created_at
`

type CreateBillImageParams struct {
	ID       pgtype.UUID `json:"id"`
	BillID   pgtype.UUID `json:"bill_id"`
	GroupID  pgtype.UUID `json:"group_id"`
	ImageKey string      `json:"image_key"`
	Position int16       `json:"position"`
}

// ============================================================================
// BILL IMAGES
// ============================================================================
func (q *Queries) CreateBillImage(ctx context.Context, arg CreateBillImageParams) (BillImage, error) {
	row := q.db.QueryRow(ctx, createBillImage,
		arg.ID,
		arg.BillID,
		arg.GroupID,
		arg.ImageKey,
		arg.Position,
	)
	var i BillImage
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.GroupID,
		&i.ImageKey,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createBillItem = `-- name: CreateBillItem :one

INSERT INTO bill_items (
    id,
    bill_id,
    group_id,
    name,
    quantity,
    unit_price,
    line_total,
    position,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now(), now()
) RETURNING id, bill_id, group_id, name, quantity, unit_price, line_total, created_at, updated_at, position
`

type CreateBillItemParams struct {
	ID        pgtype.UUID    `json:"id"`
	BillID    pgtype.UUID    `json:"bill_id"`
	GroupID   pgtype.UUID    `json:"group_id"`
	Name      string         `json:"name"`
	Quantity  pgtype.Numeric `json:"quantity"`
	UnitPrice int64          `json:"unit_price"`
	LineTotal int64          `json:"line_total"`
	Position  int16          `json:"position"`
}

// ============================================================================
// BILL ITEMS & ASSIGNMENTS
// ============================================================================
func (q *Queries) CreateBillItem(ctx context.Context, arg CreateBillItemParams) (BillItem, error) {
	row := q.db.QueryRow(ctx, createBillItem,
		arg.ID,
		arg.BillID,
		arg.GroupID,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
		arg.Position,
	)
	var i BillItem
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.GroupID,
		&i.Name,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Position,
	)
	return i, err
}

const createBillItemAssignment = `-- name: CreateBillItemAssignment :one
INSERT INTO bill_item_assignments (
    id,
    bill_item_id,
    group_id,
    member_id,
    weight,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, now()
) RETURNING id, bill_item_id, group_id, member_id, weight, created_at
`

type CreateBillItemAssignmentParams struct {
	ID         pgtype.UUID    `json:"id"`
	BillItemID pgtype.UUID    `json:"bill_item_id"`
	GroupID    pgtype.UUID    `json:"group_id"`
	MemberID   pgtype.UUID    `json:"member_id"`
	Weight     pgtype.Numeric `json:"weight"`
}

func (q *Queries) CreateBillItemAssignment(ctx context.Context, arg CreateBillItemAssignmentParams) (BillItemAssignment, error) {
	row := q.db.QueryRow(ctx, createBillItemAssignment,
		arg.ID,
		arg.BillItemID,
		arg.GroupID,
		arg.MemberID,
		arg.Weight,
	)
	var i BillItemAssignment
	err := row.Scan(
		&i.ID,
		&i.BillItemID,
		&i.GroupID,
		&i.MemberID,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const createBillShare = `-- name: CreateBillShare :one

INSERT INTO bill_shares (
    id,
    bill_id,
    group_id,
    member_id,
    computed_amount,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, now()
) RETURNING id, bill_id, group_id, member_id, computed_amount, created_at
`

type CreateBillShareParams struct {
	ID             pgtype.UUID `json:"id"`
	BillID         pgtype.UUID `json:"bill_id"`
	GroupID        pgtype.UUID `json:"group_id"`
	MemberID       pgtype.UUID `json:"member_id"`
	ComputedAmount int64       `json:"computed_amount"`
}

// ============================================================================
// BILL SHARES (Hamilton Finalized Snapshot)
// ============================================================================
func (q *Queries) CreateBillShare(ctx context.Context, arg CreateBillShareParams) (BillShare, error) {
	row := q.db.QueryRow(ctx, createBillShare,
		arg.ID,
		arg.BillID,
		arg.GroupID,
		arg.MemberID,
		arg.ComputedAmount,
	)
	var i BillShare
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.GroupID,
		&i.MemberID,
		&i.ComputedAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (
    id,
    group_id,
    bill_id,
    debtor_member_id,
    creditor_member_id,
    amount,
    status,
    reminder_count,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, 'awaiting', 0, now(), now()
) RETURNING id, group_id, bill_id, debtor_member_id, creditor_member_id, amount, status, reminder_count, payment_id, created_at, settled_at, updated_at
`

type CreateDebtParams struct {
	ID               pgtype.UUID `json:"id"`
	GroupID          pgtype.UUID `json:"group_id"`
	BillID           pgtype.UUID `json:"bill_id"`
	DebtorMemberID   pgtype.UUID `json:"debtor_member_id"`
	CreditorMemberID pgtype.UUID `json:"creditor_member_id"`
	Amount           int64       `json:"amount"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.ID,
		arg.GroupID,
		arg.BillID,
		arg.DebtorMemberID,
		arg.CreditorMemberID,
		arg.Amount,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.BillID,
		&i.DebtorMemberID,
		&i.CreditorMemberID,
		&i.Amount,
		&i.Status,
		&i.ReminderCount,
		&i.PaymentID,
		&i.CreatedAt,
		&i.SettledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOCRJob = `-- name: CreateOCRJob :one

INSERT INTO ocr_jobs (
    id,
    bill_id,
    status,
    provider,
    attempts,
    raw_response,
    candidate,
    version,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 1, now(), now()
) RETURNING id, bill_id, status, provider, attempts, raw_response, error_message, created_at, updated_at, completed_at, candidate, version
`

type CreateOCRJobParams struct {
	ID          pgtype.UUID `json:"id"`
	BillID      pgtype.UUID `json:"bill_id"`
	Status      interface{} `json:"status"`
	Provider    string      `json:"provider"`
	Attempts    int32       `json:"attempts"`
	RawResponse []byte      `json:"raw_response"`
	Candidate   []byte      `json:"candidate"`
}

// ============================================================================
// OCR JOBS
// ============================================================================
func (q *Queries) CreateOCRJob(ctx context.Context, arg CreateOCRJobParams) (OcrJob, error) {
	row := q.db.QueryRow(ctx, createOCRJob,
		arg.ID,
		arg.BillID,
		arg.Status,
		arg.Provider,
		arg.Attempts,
		arg.RawResponse,
		arg.Candidate,
	)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Status,
		&i.Provider,
		&i.Attempts,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Candidate,
		&i.Version,
	)
	return i, err
}

const deleteBillImages = `-- name: DeleteBillImages :exec
DELETE FROM bill_images
WHERE bill_id = $1
`

func (q *Queries) DeleteBillImages(ctx context.Context, billID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBillImages, billID)
	return err
}

const deleteBillItemAssignmentsByItem = `-- name: DeleteBillItemAssignmentsByItem :exec
DELETE FROM bill_item_assignments
WHERE bill_item_id = $1
`

func (q *Queries) DeleteBillItemAssignmentsByItem(ctx context.Context, billItemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBillItemAssignmentsByItem, billItemID)
	return err
}

const deleteBillItems = `-- name: DeleteBillItems :exec
DELETE FROM bill_items
WHERE bill_id = $1
`

func (q *Queries) DeleteBillItems(ctx context.Context, billID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBillItems, billID)
	return err
}

const deleteBillShares = `-- name: DeleteBillShares :exec
DELETE FROM bill_shares
WHERE bill_id = $1
`

func (q *Queries) DeleteBillShares(ctx context.Context, billID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBillShares, billID)
	return err
}

const deleteDraftBill = `-- name: DeleteDraftBill :exec
DELETE FROM bills
WHERE id = $1 AND group_id = $2 AND status = 'draft'
`

type DeleteDraftBillParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) DeleteDraftBill(ctx context.Context, arg DeleteDraftBillParams) error {
	_, err := q.db.Exec(ctx, deleteDraftBill, arg.ID, arg.GroupID)
	return err
}

const finalizeBill = `-- name: FinalizeBill :one
UPDATE bills
SET status = 'finalized',
    finalized_at = now(),
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND group_id = $2 AND status IN ('draft', 'reviewed') AND version = $3
RETURNING id, group_id, creditor_member_id, status, merchant_name, bill_date, image_object_key, subtotal, service_charge, vat, discount, total, mismatch_warning, version, created_at, finalized_at, updated_at, replaces_bill_id, voided_at, split_method, mismatch_codes
`

type FinalizeBillParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
	Version int32       `json:"version"`
}

func (q *Queries) FinalizeBill(ctx context.Context, arg FinalizeBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, finalizeBill, arg.ID, arg.GroupID, arg.Version)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreditorMemberID,
		&i.Status,
		&i.MerchantName,
		&i.BillDate,
		&i.ImageObjectKey,
		&i.Subtotal,
		&i.ServiceCharge,
		&i.Vat,
		&i.Discount,
		&i.Total,
		&i.MismatchWarning,
		&i.Version,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UpdatedAt,
		&i.ReplacesBillID,
		&i.VoidedAt,
		&i.SplitMethod,
		&i.MismatchCodes,
	)
	return i, err
}

const getActiveOCRJobByBillID = `-- name: GetActiveOCRJobByBillID :one
SELECT id, bill_id, status, provider, attempts, raw_response, error_message, created_at, updated_at, completed_at, candidate, version FROM ocr_jobs
WHERE bill_id = $1 AND status IN ('queued', 'processing')
LIMIT 1
`

func (q *Queries) GetActiveOCRJobByBillID(ctx context.Context, billID pgtype.UUID) (OcrJob, error) {
	row := q.db.QueryRow(ctx, getActiveOCRJobByBillID, billID)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Status,
		&i.Provider,
		&i.Attempts,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Candidate,
		&i.Version,
	)
	return i, err
}

const getBillByID = `-- name: GetBillByID :one
SELECT id, group_id, creditor_member_id, status, merchant_name, bill_date, image_object_key, subtotal, service_charge, vat, discount, total, mismatch_warning, version, created_at, finalized_at, updated_at, replaces_bill_id, voided_at, split_method, mismatch_codes FROM bills
WHERE id = $1 AND group_id = $2
`

type GetBillByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetBillByID(ctx context.Context, arg GetBillByIDParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillByID, arg.ID, arg.GroupID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreditorMemberID,
		&i.Status,
		&i.MerchantName,
		&i.BillDate,
		&i.ImageObjectKey,
		&i.Subtotal,
		&i.ServiceCharge,
		&i.Vat,
		&i.Discount,
		&i.Total,
		&i.MismatchWarning,
		&i.Version,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UpdatedAt,
		&i.ReplacesBillID,
		&i.VoidedAt,
		&i.SplitMethod,
		&i.MismatchCodes,
	)
	return i, err
}

const getBillByIDForUpdate = `-- name: GetBillByIDForUpdate :one
SELECT id, group_id, creditor_member_id, status, merchant_name, bill_date, image_object_key, subtotal, service_charge, vat, discount, total, mismatch_warning, version, created_at, finalized_at, updated_at, replaces_bill_id, voided_at, split_method, mismatch_codes FROM bills
WHERE id = $1 AND group_id = $2
FOR UPDATE
`

type GetBillByIDForUpdateParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) GetBillByIDForUpdate(ctx context.Context, arg GetBillByIDForUpdateParams) (Bill, error) {
	row := q.db.QueryRow(ctx, getBillByIDForUpdate, arg.ID, arg.GroupID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreditorMemberID,
		&i.Status,
		&i.MerchantName,
		&i.BillDate,
		&i.ImageObjectKey,
		&i.Subtotal,
		&i.ServiceCharge,
		&i.Vat,
		&i.Discount,
		&i.Total,
		&i.MismatchWarning,
		&i.Version,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UpdatedAt,
		&i.ReplacesBillID,
		&i.VoidedAt,
		&i.SplitMethod,
		&i.MismatchCodes,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, group_id, user_id, role, status, joined_at, left_at
FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getLatestOCRJobByBillID = `-- name: GetLatestOCRJobByBillID :one
SELECT id, bill_id, status, provider, attempts, raw_response, error_message, created_at, updated_at, completed_at, candidate, version FROM ocr_jobs
WHERE bill_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestOCRJobByBillID(ctx context.Context, billID pgtype.UUID) (OcrJob, error) {
	row := q.db.QueryRow(ctx, getLatestOCRJobByBillID, billID)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Status,
		&i.Provider,
		&i.Attempts,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Candidate,
		&i.Version,
	)
	return i, err
}

const getOCRJobByID = `-- name: GetOCRJobByID :one
SELECT id, bill_id, status, provider, attempts, raw_response, error_message, created_at, updated_at, completed_at, candidate, version FROM ocr_jobs
WHERE id = $1
`

func (q *Queries) GetOCRJobByID(ctx context.Context, id pgtype.UUID) (OcrJob, error) {
	row := q.db.QueryRow(ctx, getOCRJobByID, id)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Status,
		&i.Provider,
		&i.Attempts,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Candidate,
		&i.Version,
	)
	return i, err
}

const listActiveGroupMembers = `-- name: ListActiveGroupMembers :many
SELECT id, group_id, user_id, role, status, joined_at, left_at
FROM group_members
WHERE group_id = $1 AND status = 'active'
`

func (q *Queries) ListActiveGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listActiveGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillImages = `-- name: ListBillImages :many
SELECT id, bill_id, group_id, image_key, position, created_at FROM bill_images
WHERE bill_id = $1
ORDER BY position ASC
`

func (q *Queries) ListBillImages(ctx context.Context, billID pgtype.UUID) ([]BillImage, error) {
	rows, err := q.db.Query(ctx, listBillImages, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillImage
	for rows.Next() {
		var i BillImage
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.GroupID,
			&i.ImageKey,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillItemAssignmentsByBill = `-- name: ListBillItemAssignmentsByBill :many
SELECT a.id, a.bill_item_id, a.group_id, a.member_id, a.weight, a.created_at 
FROM bill_item_assignments a
JOIN bill_items bi ON a.bill_item_id = bi.id
WHERE bi.bill_id = $1
`

func (q *Queries) ListBillItemAssignmentsByBill(ctx context.Context, billID pgtype.UUID) ([]BillItemAssignment, error) {
	rows, err := q.db.Query(ctx, listBillItemAssignmentsByBill, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillItemAssignment
	for rows.Next() {
		var i BillItemAssignment
		if err := rows.Scan(
			&i.ID,
			&i.BillItemID,
			&i.GroupID,
			&i.MemberID,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillItemAssignmentsByItem = `-- name: ListBillItemAssignmentsByItem :many
SELECT id, bill_item_id, group_id, member_id, weight, created_at FROM bill_item_assignments
WHERE bill_item_id = $1
`

func (q *Queries) ListBillItemAssignmentsByItem(ctx context.Context, billItemID pgtype.UUID) ([]BillItemAssignment, error) {
	rows, err := q.db.Query(ctx, listBillItemAssignmentsByItem, billItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillItemAssignment
	for rows.Next() {
		var i BillItemAssignment
		if err := rows.Scan(
			&i.ID,
			&i.BillItemID,
			&i.GroupID,
			&i.MemberID,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillItems = `-- name: ListBillItems :many
SELECT id, bill_id, group_id, name, quantity, unit_price, line_total, created_at, updated_at, position FROM bill_items
WHERE bill_id = $1
ORDER BY position ASC
`

func (q *Queries) ListBillItems(ctx context.Context, billID pgtype.UUID) ([]BillItem, error) {
	rows, err := q.db.Query(ctx, listBillItems, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillItem
	for rows.Next() {
		var i BillItem
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.GroupID,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillShares = `-- name: ListBillShares :many
SELECT id, bill_id, group_id, member_id, computed_amount, created_at FROM bill_shares
WHERE bill_id = $1
`

func (q *Queries) ListBillShares(ctx context.Context, billID pgtype.UUID) ([]BillShare, error) {
	rows, err := q.db.Query(ctx, listBillShares, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillShare
	for rows.Next() {
		var i BillShare
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.GroupID,
			&i.MemberID,
			&i.ComputedAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillsByGroup = `-- name: ListBillsByGroup :many
SELECT id, group_id, creditor_member_id, status, merchant_name, bill_date, image_object_key, subtotal, service_charge, vat, discount, total, mismatch_warning, version, created_at, finalized_at, updated_at, replaces_bill_id, voided_at, split_method, mismatch_codes FROM bills
WHERE group_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBillsByGroupParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListBillsByGroup(ctx context.Context, arg ListBillsByGroupParams) ([]Bill, error) {
	rows, err := q.db.Query(ctx, listBillsByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bill
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.CreditorMemberID,
			&i.Status,
			&i.MerchantName,
			&i.BillDate,
			&i.ImageObjectKey,
			&i.Subtotal,
			&i.ServiceCharge,
			&i.Vat,
			&i.Discount,
			&i.Total,
			&i.MismatchWarning,
			&i.Version,
			&i.CreatedAt,
			&i.FinalizedAt,
			&i.UpdatedAt,
			&i.ReplacesBillID,
			&i.VoidedAt,
			&i.SplitMethod,
			&i.MismatchCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewBill = `-- name: ReviewBill :one
UPDATE bills
SET status = 'reviewed',
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND group_id = $2 AND status = 'draft' AND version = $3
RETURNING id, group_id, creditor_member_id, status, merchant_name, bill_date, image_object_key, subtotal, service_charge, vat, discount, total, mismatch_warning, version, created_at, finalized_at, updated_at, replaces_bill_id, voided_at, split_method, mismatch_codes
`

type ReviewBillParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
	Version int32       `json:"version"`
}

func (q *Queries) ReviewBill(ctx context.Context, arg ReviewBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, reviewBill, arg.ID, arg.GroupID, arg.Version)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreditorMemberID,
		&i.Status,
		&i.MerchantName,
		&i.BillDate,
		&i.ImageObjectKey,
		&i.Subtotal,
		&i.ServiceCharge,
		&i.Vat,
		&i.Discount,
		&i.Total,
		&i.MismatchWarning,
		&i.Version,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UpdatedAt,
		&i.ReplacesBillID,
		&i.VoidedAt,
		&i.SplitMethod,
		&i.MismatchCodes,
	)
	return i, err
}

const updateDraftBill = `-- name: UpdateDraftBill :one
UPDATE bills
SET merchant_name = $3,
    bill_date = $4,
    subtotal = $5,
    service_charge = $6,
    vat = $7,
    discount = $8,
    total = $9,
    split_method = $10,
    mismatch_codes = $11,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND group_id = $2 AND status = 'draft' AND version = $12
RETURNING id, group_id, creditor_member_id, status, merchant_name, bill_date, image_object_key, subtotal, service_charge, vat, discount, total, mismatch_warning, version, created_at, finalized_at, updated_at, replaces_bill_id, voided_at, split_method, mismatch_codes
`

type UpdateDraftBillParams struct {
	ID            pgtype.UUID `json:"id"`
	GroupID       pgtype.UUID `json:"group_id"`
	MerchantName  pgtype.Text `json:"merchant_name"`
	BillDate      pgtype.Date `json:"bill_date"`
	Subtotal      int64       `json:"subtotal"`
	ServiceCharge int64       `json:"service_charge"`
	Vat           int64       `json:"vat"`
	Discount      int64       `json:"discount"`
	Total         int64       `json:"total"`
	SplitMethod   string      `json:"split_method"`
	MismatchCodes []string    `json:"mismatch_codes"`
	Version       int32       `json:"version"`
}

func (q *Queries) UpdateDraftBill(ctx context.Context, arg UpdateDraftBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateDraftBill,
		arg.ID,
		arg.GroupID,
		arg.MerchantName,
		arg.BillDate,
		arg.Subtotal,
		arg.ServiceCharge,
		arg.Vat,
		arg.Discount,
		arg.Total,
		arg.SplitMethod,
		arg.MismatchCodes,
		arg.Version,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreditorMemberID,
		&i.Status,
		&i.MerchantName,
		&i.BillDate,
		&i.ImageObjectKey,
		&i.Subtotal,
		&i.ServiceCharge,
		&i.Vat,
		&i.Discount,
		&i.Total,
		&i.MismatchWarning,
		&i.Version,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UpdatedAt,
		&i.ReplacesBillID,
		&i.VoidedAt,
		&i.SplitMethod,
		&i.MismatchCodes,
	)
	return i, err
}

const updateOCRJobFailed = `-- name: UpdateOCRJobFailed :one
UPDATE ocr_jobs
SET status = 'failed',
    error_message = $3,
    version = version + 1,
    updated_at = now(),
    completed_at = now()
WHERE id = $1 AND version = $2
RETURNING id, bill_id, status, provider, attempts, raw_response, error_message, created_at, updated_at, completed_at, candidate, version
`

type UpdateOCRJobFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	Version      int32       `json:"version"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateOCRJobFailed(ctx context.Context, arg UpdateOCRJobFailedParams) (OcrJob, error) {
	row := q.db.QueryRow(ctx, updateOCRJobFailed, arg.ID, arg.Version, arg.ErrorMessage)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Status,
		&i.Provider,
		&i.Attempts,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Candidate,
		&i.Version,
	)
	return i, err
}

const updateOCRJobProcessing = `-- name: UpdateOCRJobProcessing :one
UPDATE ocr_jobs
SET status = 'processing',
    attempts = attempts + 1,
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND version = $2
RETURNING id, bill_id, status, provider, attempts, raw_response, error_message, created_at, updated_at, completed_at, candidate, version
`

type UpdateOCRJobProcessingParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int32       `json:"version"`
}

func (q *Queries) UpdateOCRJobProcessing(ctx context.Context, arg UpdateOCRJobProcessingParams) (OcrJob, error) {
	row := q.db.QueryRow(ctx, updateOCRJobProcessing, arg.ID, arg.Version)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Status,
		&i.Provider,
		&i.Attempts,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Candidate,
		&i.Version,
	)
	return i, err
}

const updateOCRJobSuccess = `-- name: UpdateOCRJobSuccess :one
UPDATE ocr_jobs
SET status = 'succeeded',
    candidate = $3,
    raw_response = $4,
    version = version + 1,
    updated_at = now(),
    completed_at = now()
WHERE id = $1 AND version = $2
RETURNING id, bill_id, status, provider, attempts, raw_response, error_message, created_at, updated_at, completed_at, candidate, version
`

type UpdateOCRJobSuccessParams struct {
	ID          pgtype.UUID `json:"id"`
	Version     int32       `json:"version"`
	Candidate   []byte      `json:"candidate"`
	RawResponse []byte      `json:"raw_response"`
}

func (q *Queries) UpdateOCRJobSuccess(ctx context.Context, arg UpdateOCRJobSuccessParams) (OcrJob, error) {
	row := q.db.QueryRow(ctx, updateOCRJobSuccess,
		arg.ID,
		arg.Version,
		arg.Candidate,
		arg.RawResponse,
	)
	var i OcrJob
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.Status,
		&i.Provider,
		&i.Attempts,
		&i.RawResponse,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.Candidate,
		&i.Version,
	)
	return i, err
}

const voidBill = `-- name: VoidBill :one
UPDATE bills
SET status = 'voided',
    voided_at = now(),
    version = version + 1,
    updated_at = now()
WHERE id = $1 AND group_id = $2 AND status = 'finalized' AND version = $3
RETURNING id, group_id, creditor_member_id, status, merchant_name, bill_date, image_object_key, subtotal, service_charge, vat, discount, total, mismatch_warning, version, created_at, finalized_at, updated_at, replaces_bill_id, voided_at, split_method, mismatch_codes
`

type VoidBillParams struct {
	ID      pgtype.UUID `json:"id"`
	GroupID pgtype.UUID `json:"group_id"`
	Version int32       `json:"version"`
}

func (q *Queries) VoidBill(ctx context.Context, arg VoidBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, voidBill, arg.ID, arg.GroupID, arg.Version)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.CreditorMemberID,
		&i.Status,
		&i.MerchantName,
		&i.BillDate,
		&i.ImageObjectKey,
		&i.Subtotal,
		&i.ServiceCharge,
		&i.Vat,
		&i.Discount,
		&i.Total,
		&i.MismatchWarning,
		&i.Version,
		&i.CreatedAt,
		&i.FinalizedAt,
		&i.UpdatedAt,
		&i.ReplacesBillID,
		&i.VoidedAt,
		&i.SplitMethod,
		&i.MismatchCodes,
	)
	return i, err
}

const voidDebtsByBillID = `-- name: VoidDebtsByBillID :exec
UPDATE debts
SET status = 'voided',
    updated_at = now()
WHERE bill_id = $1 AND status = 'awaiting'
`

func (q *Queries) VoidDebtsByBillID(ctx context.Context, billID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, voidDebtsByBillID, billID)
	return err
}
