// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	AdminID      pgtype.UUID        `json:"admin_id"`
	TargetUserID pgtype.UUID        `json:"target_user_id"`
	Action       interface{}        `json:"action"`
	Reason       string             `json:"reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuthRateLimitEvent struct {
	ID         pgtype.UUID        `json:"id"`
	Action     string             `json:"action"`
	Dimension  string             `json:"dimension"`
	KeyHash    []byte             `json:"key_hash"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

type Bill struct {
	ID                 pgtype.UUID        `json:"id"`
	GroupID            pgtype.UUID        `json:"group_id"`
	CreditorMemberID   pgtype.UUID        `json:"creditor_member_id"`
	Status             interface{}        `json:"status"`
	MerchantName       pgtype.Text        `json:"merchant_name"`
	BillDate           pgtype.Date        `json:"bill_date"`
	ImageObjectKey     pgtype.Text        `json:"image_object_key"`
	Subtotal           int64              `json:"subtotal"`
	ServiceCharge      int64              `json:"service_charge"`
	Vat                int64              `json:"vat"`
	Discount           int64              `json:"discount"`
	Total              int64              `json:"total"`
	MismatchWarning    bool               `json:"mismatch_warning"`
	Version            int32              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FinalizedAt        pgtype.Timestamptz `json:"finalized_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ReplacesBillID     pgtype.UUID        `json:"replaces_bill_id"`
	VoidedAt           pgtype.Timestamptz `json:"voided_at"`
	SplitMethod        string             `json:"split_method"`
	MismatchCodes      []string           `json:"mismatch_codes"`
	ReviewedAt         pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedByMemberID pgtype.UUID        `json:"reviewed_by_member_id"`
}

type BillImage struct {
	ID        pgtype.UUID        `json:"id"`
	BillID    pgtype.UUID        `json:"bill_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	ImageKey  string             `json:"image_key"`
	Position  int16              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BillItem struct {
	ID        pgtype.UUID        `json:"id"`
	BillID    pgtype.UUID        `json:"bill_id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Name      string             `json:"name"`
	Quantity  pgtype.Numeric     `json:"quantity"`
	UnitPrice int64              `json:"unit_price"`
	LineTotal int64              `json:"line_total"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Position  int16              `json:"position"`
}

type BillItemAssignment struct {
	ID         pgtype.UUID        `json:"id"`
	BillItemID pgtype.UUID        `json:"bill_item_id"`
	GroupID    pgtype.UUID        `json:"group_id"`
	MemberID   pgtype.UUID        `json:"member_id"`
	Weight     pgtype.Numeric     `json:"weight"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BillShare struct {
	ID                 pgtype.UUID        `json:"id"`
	BillID             pgtype.UUID        `json:"bill_id"`
	GroupID            pgtype.UUID        `json:"group_id"`
	MemberID           pgtype.UUID        `json:"member_id"`
	ItemSubtotal       int64              `json:"item_subtotal"`
	ServiceChargeShare int64              `json:"service_charge_share"`
	VatShare           int64              `json:"vat_share"`
	DiscountShare      int64              `json:"discount_share"`
	RoundingAdjustment int64              `json:"rounding_adjustment"`
	FinalAmount        int64              `json:"final_amount"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Debt struct {
	ID               pgtype.UUID        `json:"id"`
	GroupID          pgtype.UUID        `json:"group_id"`
	BillID           pgtype.UUID        `json:"bill_id"`
	DebtorMemberID   pgtype.UUID        `json:"debtor_member_id"`
	CreditorMemberID pgtype.UUID        `json:"creditor_member_id"`
	Amount           int64              `json:"amount"`
	Status           interface{}        `json:"status"`
	ReminderCount    int32              `json:"reminder_count"`
	PaymentID        pgtype.UUID        `json:"payment_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SettledAt        pgtype.Timestamptz `json:"settled_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Group struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Currency  string             `json:"currency"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupActivity struct {
	ID            pgtype.UUID        `json:"id"`
	GroupID       pgtype.UUID        `json:"group_id"`
	ActorMemberID pgtype.UUID        `json:"actor_member_id"`
	ActionType    interface{}        `json:"action_type"`
	Description   string             `json:"description"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type GroupInvite struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	Code      string             `json:"code"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   pgtype.Int4        `json:"max_uses"`
	UseCount  int32              `json:"use_count"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GroupMember struct {
	ID       pgtype.UUID        `json:"id"`
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     interface{}        `json:"role"`
	Status   interface{}        `json:"status"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
	LeftAt   pgtype.Timestamptz `json:"left_at"`
}

type MediaCleanupJob struct {
	ID            pgtype.UUID        `json:"id"`
	Provider      string             `json:"provider"`
	ObjectKey     string             `json:"object_key"`
	AttemptCount  int32              `json:"attempt_count"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	LastErrorCode pgtype.Text        `json:"last_error_code"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
}

type OcrJob struct {
	ID           pgtype.UUID        `json:"id"`
	BillID       pgtype.UUID        `json:"bill_id"`
	Status       interface{}        `json:"status"`
	Provider     string             `json:"provider"`
	Attempts     int32              `json:"attempts"`
	RawResponse  []byte             `json:"raw_response"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	Candidate    []byte             `json:"candidate"`
	Version      int32              `json:"version"`
}

type Payment struct {
	ID               pgtype.UUID        `json:"id"`
	GroupID          pgtype.UUID        `json:"group_id"`
	DebtorMemberID   pgtype.UUID        `json:"debtor_member_id"`
	CreditorMemberID pgtype.UUID        `json:"creditor_member_id"`
	Amount           int64              `json:"amount"`
	ReferenceCode    string             `json:"reference_code"`
	QrPayload        pgtype.Text        `json:"qr_payload"`
	ImageObjectKey   pgtype.Text        `json:"image_object_key"`
	Note             pgtype.Text        `json:"note"`
	RejectionReason  pgtype.Text        `json:"rejection_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SubmittedAt      pgtype.Timestamptz `json:"submitted_at"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
	RejectedAt       pgtype.Timestamptz `json:"rejected_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DeviceID      pgtype.UUID        `json:"device_id"`
	DeviceName    pgtype.Text        `json:"device_name"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	FcmToken      pgtype.Text        `json:"fcm_token"`
}

type SessionRefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	TokenHash []byte             `json:"token_hash"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID                         pgtype.UUID        `json:"id"`
	Email                      string             `json:"email"`
	PasswordHash               string             `json:"password_hash"`
	DisplayName                string             `json:"display_name"`
	AvatarObjectKey            pgtype.Text        `json:"avatar_object_key"`
	PhoneNumber                string             `json:"phone_number"`
	DefaultBankCode            pgtype.Text        `json:"default_bank_code"`
	DefaultBankAccountNumber   pgtype.Text        `json:"default_bank_account_number"`
	DefaultBankAccountHolder   pgtype.Text        `json:"default_bank_account_holder"`
	Role                       interface{}        `json:"role"`
	Status                     interface{}        `json:"status"`
	EmailVerifiedAt            pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	FailedLoginCount           int32              `json:"failed_login_count"`
	FailedLoginWindowStartedAt pgtype.Timestamptz `json:"failed_login_window_started_at"`
	LoginBlockedUntil          pgtype.Timestamptz `json:"login_blocked_until"`
}

type UserToken struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Type         interface{}        `json:"type"`
	TokenHash    []byte             `json:"token_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	SupersededAt pgtype.Timestamptz `json:"superseded_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type VMemberBalance struct {
	GroupID    pgtype.UUID `json:"group_id"`
	MemberID   pgtype.UUID `json:"member_id"`
	NetBalance int32       `json:"net_balance"`
}
