// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountManualOCRAttemptsInWindow(ctx context.Context, arg CountManualOCRAttemptsInWindowParams) (int64, error)
	CountNonAwaitingDebtsByBillID(ctx context.Context, billID pgtype.UUID) (int64, error)
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	// ============================================================================
	// BILL IMAGES
	// ============================================================================
	CreateBillImage(ctx context.Context, arg CreateBillImageParams) (BillImage, error)
	// ============================================================================
	// BILL ITEMS & ASSIGNMENTS
	// ============================================================================
	CreateBillItem(ctx context.Context, arg CreateBillItemParams) (BillItem, error)
	CreateBillItemAssignment(ctx context.Context, arg CreateBillItemAssignmentParams) (BillItemAssignment, error)
	// ============================================================================
	// BILL SHARES (Hamilton Finalized Snapshot)
	// ============================================================================
	CreateBillShare(ctx context.Context, arg CreateBillShareParams) (BillShare, error)
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error)
	// ============================================================================
	// OCR JOBS
	// ============================================================================
	CreateOCRJob(ctx context.Context, arg CreateOCRJobParams) (OcrJob, error)
	DeleteBillImages(ctx context.Context, billID pgtype.UUID) error
	DeleteBillItemAssignmentsByItem(ctx context.Context, billItemID pgtype.UUID) error
	DeleteBillItems(ctx context.Context, billID pgtype.UUID) error
	DeleteBillShares(ctx context.Context, billID pgtype.UUID) error
	DeleteDraftBill(ctx context.Context, arg DeleteDraftBillParams) (int64, error)
	FinalizeBill(ctx context.Context, arg FinalizeBillParams) (Bill, error)
	GetActiveOCRJobByBillID(ctx context.Context, billID pgtype.UUID) (OcrJob, error)
	GetBillByID(ctx context.Context, arg GetBillByIDParams) (Bill, error)
	GetBillByIDForUpdate(ctx context.Context, arg GetBillByIDForUpdateParams) (Bill, error)
	GetBillOnlyByID(ctx context.Context, id pgtype.UUID) (GetBillOnlyByIDRow, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetGroupMemberUser(ctx context.Context, arg GetGroupMemberUserParams) (GetGroupMemberUserRow, error)
	GetLatestOCRJobByBillID(ctx context.Context, billID pgtype.UUID) (OcrJob, error)
	GetOCRJobByID(ctx context.Context, id pgtype.UUID) (OcrJob, error)
	InsertGroupActivity(ctx context.Context, arg InsertGroupActivityParams) (GroupActivity, error)
	ListActiveGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMember, error)
	ListBillImages(ctx context.Context, billID pgtype.UUID) ([]BillImage, error)
	ListBillItemAssignmentsByBill(ctx context.Context, billID pgtype.UUID) ([]BillItemAssignment, error)
	ListBillItemAssignmentsByItem(ctx context.Context, billItemID pgtype.UUID) ([]BillItemAssignment, error)
	ListBillItems(ctx context.Context, billID pgtype.UUID) ([]BillItem, error)
	ListBillShares(ctx context.Context, billID pgtype.UUID) ([]BillShare, error)
	ListBillsByGroup(ctx context.Context, arg ListBillsByGroupParams) ([]Bill, error)
	ListBillsByGroupCursor(ctx context.Context, arg ListBillsByGroupCursorParams) ([]Bill, error)
	ReviewBill(ctx context.Context, arg ReviewBillParams) (Bill, error)
	UpdateDraftBill(ctx context.Context, arg UpdateDraftBillParams) (Bill, error)
	UpdateOCRJobFailed(ctx context.Context, arg UpdateOCRJobFailedParams) (OcrJob, error)
	UpdateOCRJobProcessing(ctx context.Context, arg UpdateOCRJobProcessingParams) (OcrJob, error)
	UpdateOCRJobSuccess(ctx context.Context, arg UpdateOCRJobSuccessParams) (OcrJob, error)
	VoidBill(ctx context.Context, arg VoidBillParams) (Bill, error)
	VoidDebtsByBillID(ctx context.Context, billID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
