// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CaptureOpenBills(ctx context.Context, groupID pgtype.UUID) ([]CaptureOpenBillsRow, error)
	CompleteFinalizeBatch(ctx context.Context, arg CompleteFinalizeBatchParams) (int64, error)
	CountActiveBatchesForGroup(ctx context.Context, groupID pgtype.UUID) (int64, error)
	// Nguồn sự thật cho gauge paysplit_ocr_queue_depth: đếm trực tiếp trên bảng thay vì cộng/trừ trong
	// tiến trình, để chính xác qua restart, rollback và nhiều replica (Spec 3 AC-14).
	CountActiveOCRJobs(ctx context.Context) (int64, error)
	// Đếm hóa đơn theo từng trạng thái để badge của các chip lọc không phụ thuộc
	// vào trang dữ liệu đã tải.
	CountBillsByGroupStatus(ctx context.Context, groupID pgtype.UUID) ([]CountBillsByGroupStatusRow, error)
	CountManualOCRAttemptsInWindow(ctx context.Context, arg CountManualOCRAttemptsInWindowParams) (int64, error)
	CountNonAwaitingDebtsByBillID(ctx context.Context, billID pgtype.UUID) (int64, error)
	CountPendingBatchItems(ctx context.Context, batchID pgtype.UUID) (int64, error)
	CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error)
	// ============================================================================
	// BILL IMAGES
	// ============================================================================
	CreateBillImage(ctx context.Context, arg CreateBillImageParams) (BillImage, error)
	// ============================================================================
	// BILL ITEMS & ASSIGNMENTS
	// ============================================================================
	CreateBillItem(ctx context.Context, arg CreateBillItemParams) (BillItem, error)
	CreateBillItemAssignment(ctx context.Context, arg CreateBillItemAssignmentParams) (BillItemAssignment, error)
	// ============================================================================
	// BILL SHARES (Hamilton Finalized Snapshot)
	// ============================================================================
	CreateBillShare(ctx context.Context, arg CreateBillShareParams) (BillShare, error)
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error)
	// ============================================================================
	// NOTIFICATIONS & CLEANUP (Transactional inserts during bill lifecycle)
	// ============================================================================
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// ============================================================================
	// OCR JOBS
	// ============================================================================
	CreateOCRJob(ctx context.Context, arg CreateOCRJobParams) (OcrJob, error)
	DeleteBillImages(ctx context.Context, billID pgtype.UUID) error
	DeleteBillItemAssignmentsByItem(ctx context.Context, billItemID pgtype.UUID) error
	DeleteBillItems(ctx context.Context, billID pgtype.UUID) error
	DeleteBillShares(ctx context.Context, billID pgtype.UUID) error
	DeleteDraftBill(ctx context.Context, arg DeleteDraftBillParams) (int64, error)
	FinalizeBill(ctx context.Context, arg FinalizeBillParams) (Bill, error)
	GetActiveCaptainMembership(ctx context.Context, groupID pgtype.UUID) (GroupMember, error)
	GetActiveFinalizeBatch(ctx context.Context, groupID pgtype.UUID) ([]GroupBillFinalizeBatch, error)
	GetActiveOCRJobByBillID(ctx context.Context, billID pgtype.UUID) (OcrJob, error)
	GetBillByID(ctx context.Context, arg GetBillByIDParams) (Bill, error)
	GetBillByIDForUpdate(ctx context.Context, arg GetBillByIDForUpdateParams) (Bill, error)
	GetBillOnlyByID(ctx context.Context, id pgtype.UUID) (GetBillOnlyByIDRow, error)
	// Rào chắn archive với batch đang chạy được kiểm tra trong code (DisbandGroup
	// của module group) ngay sau khi giữ khóa nhóm, không dùng trigger.
	// ============================================================================
	// BATCH ITEM WORKER SUPPORT (đọc trong transaction của item)
	// ============================================================================
	GetBillStateForBatch(ctx context.Context, arg GetBillStateForBatchParams) (GetBillStateForBatchRow, error)
	GetFinalizeBatchByID(ctx context.Context, arg GetFinalizeBatchByIDParams) (GroupBillFinalizeBatch, error)
	GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error)
	GetGroupMemberUser(ctx context.Context, arg GetGroupMemberUserParams) (GetGroupMemberUserRow, error)
	// ============================================================================
	// GROUP BILL CLOSE V1 (Spec 0008)
	// Khóa gửi hóa đơn một chiều, batch chốt toàn bộ và item xử lý từng bill.
	// ============================================================================
	GetGroupSubmissionLock(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error)
	GetLatestFinalizeBatch(ctx context.Context, groupID pgtype.UUID) (GroupBillFinalizeBatch, error)
	GetLatestOCRJobByBillID(ctx context.Context, billID pgtype.UUID) (OcrJob, error)
	GetOCRJobByID(ctx context.Context, id pgtype.UUID) (OcrJob, error)
	IncrementBatchFailedCount(ctx context.Context, id pgtype.UUID) (int64, error)
	IncrementBatchFinalizedCount(ctx context.Context, id pgtype.UUID) (int64, error)
	InsertFinalizeBatch(ctx context.Context, arg InsertFinalizeBatchParams) (GroupBillFinalizeBatch, error)
	InsertFinalizeItem(ctx context.Context, arg InsertFinalizeItemParams) (int64, error)
	InsertGroupActivity(ctx context.Context, arg InsertGroupActivityParams) (GroupActivity, error)
	InsertMediaCleanupJob(ctx context.Context, arg InsertMediaCleanupJobParams) error
	ListActiveGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]GroupMember, error)
	ListBatchItemsPage(ctx context.Context, arg ListBatchItemsPageParams) ([]ListBatchItemsPageRow, error)
	ListBillImages(ctx context.Context, billID pgtype.UUID) ([]BillImage, error)
	ListBillItemAssignmentsByBill(ctx context.Context, billID pgtype.UUID) ([]BillItemAssignment, error)
	ListBillItemAssignmentsByItem(ctx context.Context, billItemID pgtype.UUID) ([]BillItemAssignment, error)
	ListBillItems(ctx context.Context, billID pgtype.UUID) ([]BillItem, error)
	ListBillShares(ctx context.Context, billID pgtype.UUID) ([]BillShare, error)
	ListBillsByGroup(ctx context.Context, arg ListBillsByGroupParams) ([]ListBillsByGroupRow, error)
	ListBillsByGroupCursor(ctx context.Context, arg ListBillsByGroupCursorParams) ([]ListBillsByGroupCursorRow, error)
	ListDebtsByBillIDForUpdate(ctx context.Context, billID pgtype.UUID) ([]Debt, error)
	LockBatchItemForUpdate(ctx context.Context, arg LockBatchItemForUpdateParams) (GroupBillFinalizeItem, error)
	LockBatchRowForUpdate(ctx context.Context, id pgtype.UUID) (GroupBillFinalizeBatch, error)
	MarkBatchItemFailed(ctx context.Context, arg MarkBatchItemFailedParams) (int64, error)
	MarkBatchItemFinalized(ctx context.Context, arg MarkBatchItemFinalizedParams) (int64, error)
	PromoteBatchToProcessing(ctx context.Context, id pgtype.UUID) (int64, error)
	ReviewBill(ctx context.Context, arg ReviewBillParams) (Bill, error)
	SetGroupSubmissionLockedAt(ctx context.Context, id pgtype.UUID) (pgtype.Timestamptz, error)
	UpdateDraftBill(ctx context.Context, arg UpdateDraftBillParams) (Bill, error)
	UpdateOCRJobFailed(ctx context.Context, arg UpdateOCRJobFailedParams) (OcrJob, error)
	UpdateOCRJobProcessing(ctx context.Context, id pgtype.UUID) (OcrJob, error)
	UpdateOCRJobSuccess(ctx context.Context, arg UpdateOCRJobSuccessParams) (OcrJob, error)
	VoidBill(ctx context.Context, arg VoidBillParams) (Bill, error)
	VoidDebtsByBillID(ctx context.Context, billID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
